* reading notes

** programming code (for scraping)
** articles, essays, reports
**** DONE "OpenAI’s proposals for the U.S. AI Action Plan," 2025 OSTP proposal, March 13, 2025
CLOSED: [2026-07-17 Fri 12:55]
- Office of Science and Technology Policy proposal
- proposals to help OSTP develop "AI Action Plan ... that ensure[s]
  that American-led AI built on democratic principles continues to
  prevail over CCP-built autocratic, authoritarian AI".
- "democratic AI"
  - "a free market promoting free and fair competition.
  - "freedom for developers and users to work with our tools"
  - "preventing government use... to amass power and control their
    citizens"
- Positioning against China to create urgency for proposals. 
  - Deepseek is a threat because "simultaneously state-subsidized,
    state-controlled, and fully available... cost[ing] users privacy
    and security."
- point #3: "Copyright: Promoting the Freedom to Learn"
  - need to use copyrighted material to compete with China, a "matter
    of national security."
  - contradiction between China's "unfettered access" vs OpenAI's
    "fair use":
    - "Applying the fair use doctrine to AI is not only a matter of
      American competitiveness-—it’s a matter of national security.
      The rapid advances seen with the PRC’s DeepSeek, among other
      recent developments, show that America’s lead on frontier AI is
      far from guaranteed. Given concerted state support for critical
      industries and infrastructure projects, there’s little doubt
      that the PRC’s AI developers will enjoy unfettered access to
      data—including copyrighted data—that will improve their models.
      If the PRC’s developers have unfettered access to data and
      American companies are left without fair use access, the race
      for AI is effectively over. America loses, as does the success
      of democratic AI. Ultimately, access to more data from the
      widest possible range of sources will ensure more access to more
      powerful innovations that deliver even more knowledge" (10-11).
**** DONE Bennke, Johannes, and Nathan Schneider. Protological Governance. Between Sovereignty and Entanglement. With mediarep.org, 2025. DOI.org (Datacite), https://doi.org/10.25969/MEDIAREP/23996.
CLOSED: [2026-07-17 Fri 12:55]
"Protocol" is "a pattern that organizes modes of interaction among
agents" (Bennke & Scheider 15).

"in order to attain the sovereignty that participants aspire
toward, protocological systems must also be understood as spaces of
entanglement and embodiment, never fully describable or possible to
separate from the lived experience of their participants" (Bennke &
Schneider 32). 

"Protocological governance, we propose, occurs when protocols
themselves become sites of sovereignty, governing according to a logic
not reducible to any of the entities entangled with them. It is a form
of socio-technical organization, and a rule-based system for
coordinating interactions, whose dominant logic operates through
protocols" (Bennke & Schneider 16).

"protocological chiasm, a dynamic tension by which protocols can
resist capture by other forces through embodied performance" (Bennke &
Schneider 17).

"A protocol becomes meaningful through the embodied performances of
mutual entanglement among its participants. In turn, protocols
generate a kind of sovereignty when their logic is not reducible to
any one participant’s control. Sovereignty, here, is not constituted
by a link to the nation state but by the capacity for a protocol to
resist subjugation to any external force" (Bennke & Schneider 30). 

"Protocological governance becomes possible when a patterned
interaction is sufficiently sovereign to resist capture but also
sufficiently entangled to be legitimate and to operate according to a
logic not reducible to any of its participants" (Bennke & Schneider
26).

Web3 has been proposed as a "zero-trust" method that can elude
capture, but it has been re-centralized by cypto miners with more
captial to invest in hardware (Bennke & Schneider 28).

The "chiasm"
- "the chiasm as a concept to relate sovereignty and entanglement in
  protocological governance" (Bennke & Schneider 31).
- "This ontology of chiasm describes the entangled, noncoincidental
  nature of sensible experience, where beings co-belong without fully
  coinciding... The chiasm signifies embodied heteronomy, where
  indeterminate forces emerge through entanglements" (Bennke &
  Schneider 31).
- "the chiasm indicates an interdependence, co-creation, and
  hybridization in the entanglement among its members. Values such as
  openness, privacy, freedom, and security are not conferred by the
  protocol in the abstract, they also must be put into practice
  through performance. In turn, the protocol inscribes its logic back
  into those values" (Bennke & Schneider 31).


**** DONE Varoquaux, Gaël, et al. “Hype, Sustainability, and the Price of the Bigger-Is-Better Paradigm in AI.” arXiv:2409.14160, arXiv, 1 Mar. 2025. arXiv.org, https://doi.org/10.48550/arXiv.2409.14160.
CLOSED: [2026-08-12 Wed 10:28]
“the narrative that the larger the AI system the more valuable,
powerful and interesting it is is increasingly seen as common sense.
But what is this assumption based on, and how are we measuring value,
power, and performance?” ([Varoquaux et al., 2025, p.
1](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=1&annotation=LQWIF58T))

“refute two common assumptions underlying the ‘bigger-is-better’ AI
paradigm: 1) that performance improvements are driven by increased
scale, and 2) that all interesting problems addressed by AI require
large-scale models.” ([Varoquaux et al., 2025, p.
1](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=1&annotation=8RWIRK8X))

“exacerbates a concentration of power, which centralizes
decision-making in the hands of a few actors while threatening to
disempower others” ([Varoquaux et al., 2025, p.
1](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=1&annotation=CT2UNL2P))

“We argue not that scale isn’t useful, in some cases, but that there
is too much focus on scale and not enough value on other research”
([Varoquaux et al., 2025, p.
1](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=1&annotation=3GYWEICD))

“finding that scale is not well correlated with better performance in
certain contexts, and in fact benefits of scale tend to saturate”
([Varoquaux et al., 2025, p.
2](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=2&annotation=UAD6IZMY))

“the drive for more and more data encourages unethical and unauditable
data practices (Section 4)” ([Varoquaux et al., 2025, p.
2](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=2&annotation=SYU7VQP5))

“On many tasks, benchmark performance as a function of scale tends to
saturate after a certain point (see Figure 2)” ([Varoquaux et al.,
2025, p. 3](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=3&annotation=7J54XDXP))

“a proposal made by Wagstaff over a decade ago called for ML with
meaningful applications, each of which calls for approaches adapted to
its constraints (Wagstaff, 2012), a philosophy that has become
decidedly unpopular in recent years in the pursuit of
‘general-purpose’ AI models” ([Varoquaux et al., 2025, p.
4](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=4&annotation=KECEHH38))

“for applied ML research what often matters most – even if we focus on
simple purpose-specific metrics – is to address well-defined and
application-specific goals while respecting the compute constraints at
hand. And doing so often benefits from smaller, purpose-specific
approaches as opposed to larger, more generic models” ([Varoquaux et
al., 2025, p. 4](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=4&annotation=APJFJ69B))

“the most frequently used ML models are linear models and tree-based ones (Kumar, 2022).” ([Varoquaux et al., 2025, p. 4](zotero://select/library/items/RTDRRBA8)) ([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=4&annotation=MB9RBQ62))

“focus on smaller models also unearths myriad unresolved scientific
questions, which remain in need of scrutiny and innovative thinking
independent of scale” ([Varoquaux et al., 2025, p.
4](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=4&annotation=YPTNQG5I))

“one of the main reasons ML practitioners are drawn to scale is that
large scale models have, over the past decade or more, beaten smaller
models, as measured by these benchmarks. And beating the benchmark is
currently how SOTA is defined (and how best paper awards are allotted,
tenure given, funding secured, etc.)” ([Varoquaux et al., 2025, p.
4](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=4&annotation=VMB6YUDG))

“ML benchmarks and evaluations remain unrepresentative proxies of
downstream model performance, and are not a substitute for more
holistic assessments. Importantly, such benchmarks cannot speak to
whether a given model is suited to a given purpose and context.”
([Varoquaux et al., 2025, p.
5](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=5&annotation=9ZY5548N))

“It is well-known phenomenon in economics that when the efficiency of
a general-use technology increases, the falling costs lead to an
increased demand, resulting in an overall increase in resource usage.
This is referred to as “Jevons Paradox” (Jevons, 1865)” ([Varoquaux et
al., 2025, p. 5](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=5&annotation=XSQLCLQC))

“In fact, recent research on the LAION datasets showed that as these
datasets grow in size, the issues that plague them also multiply, with
larger datasets contain disproportionally more problematic content
than smaller datasets (Birhane et al., 2023).” ([Varoquaux et al.,
2025, p. 7](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=7&annotation=W6DNKAYA))

“As the field works with ever larger datasets, we are also incurring
more and more ‘documentation debt’ wherein training datasets are too
large to document both during creation and post-hoc (Bender et al.,
2021)” ([Varoquaux et al., 2025, p.
7](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=7&annotation=IV2QJ3BY))

“the majority of the revenue of the Big Tech companies leading the AI
revolution comes from targeted advertising - representing 80% of
Google’s (Alphabet, 2023) and 90% of Meta’s (Meta, 2023a;b) annual
revenue in 2022” ([Varoquaux et al., 2025, p.
7](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=7&annotation=ZMCHANQ5))

“These circular investment deals can blur the boundary between
“investment” and “acquisition”.” ([Varoquaux et al., 2025, p.
8](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=8&annotation=I9TKT2V6))

“We see this dynamic at play in OpenAI’s shifting stance and policies
as they have become more closely tied to Microsoft, a choice they made
admittedly to access scarce computational resources. This is
illustrated by the 2024 change to their acceptable use policy, which
significantly softened the proscription against using their products
for “military and warfare”; this change unlocked new revenue streams
(Stone and MBergen, 2024), connected OpenAI’s large scale AI to
Microsoft’s existing US military partnerships (Xiang, 2023), and later
pushed AI to direct battlefield application via a partnership with the
defense-tech company Anduril (O’Donnell, 2024).” ([Varoquaux et al.,
2025, p. 9](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=9&annotation=AYMICPRS))

“We should consider how such concentrated power with agency over
centralized AI could shape society under more authoritarian
conditions.” ([Varoquaux et al., 2025, p.
9](zotero://select/library/items/RTDRRBA8))
([pdf](zotero://open-pdf/library/items/V2NSBWTH?page=9&annotation=UI2MXSRG))

**** Meyer, Null. 9. Paradoxes of Openness: Power, Reciprocity, and the Governance of Scholarly Infrastructures. May 2026, pp. 181–206. www.openbookpublishers.com, https://doi.org/10.11647/obp.0528.09.
**** Vallas and Schor, "What Do Platforms Do?"
**** Cohen, Julie. /Between Truth and Power: The Legal Constructions of Informational Capitalism/, 2019
**** Cohen, Julie. "Oligarchy, State, and Cryptopia," 2025.
**** Warner et al., "Slow, Painful and Expensive: Current Challenges in Text-Mining Corpus Construction for the Digital Humanities." /DHQ/. 2025.
**** Warwick, /Radical Tactics of the Offline Library/ 2014.
** books
*** to read/re-read
- [X] Galloway, /Protocol/
- [X] Coulry & Miejas, /Data Grab/
- [ ] Moore, /Publishing Beyond the Market/
- [ ] Chun, /Control & Freedom/
- [ ] Ludovico, /Tactical Publishing/
- [ ] Lessig, /Code/
- [ ] Paris, /Radical Infrastructures/
- [ ] Anzaldua, /Las Fronteras/
- [ ] Anzaldua, /Entrevistas/

*** maybe
- Books by Castillo and Castanedas on immigration
- essay by Shutte
  
** congressional documents

*** searches

**** Getting gender, women, children

(gender OR sex) OR (women AND sports) OR (women AND protecting NOT
health) OR (women AND protection NOT health) OR (women AND protect NOT
health) OR (children AND protecting NOT health) OR (children AND
protection NOT health) OR (children AND protect NOT health)

https://www.congress.gov/quick-search/congressional-record?wordsPhrases=%28gender+OR+sex%29+OR+%28women+AND+sports%29+OR+%28women+AND+protecting+NOT+health%29+OR+%28women+AND+protection+NOT+health%29+OR+%28women+AND+protect+NOT+health%29+OR+%28children+AND+protecting+NOT+health%29+OR+%28children+AND+protection+NOT+health%29+OR+%28children+AND+protect+NOT+health%29+%0D%0A&wordVariants=on&searchIn=on&congressGroups%5B0%5D=0&congresses%5B0%5D=119&congresses%5B1%5D=118&congresses%5B2%5D=117&congresses%5B3%5D=116&dateOperator=equal&startDate=&endDate=&dateIsOption=yesterday&sectionDailyDigest=on&sectionSenate=on&sectionHouse=on&sectionExtensionsOfRemarks=on&representative%5B0%5D=&senator%5B0%5D=

**** getting gender ideology or biological sex???

**** getting protecting women or children???

*** SENATE RESOLUTION 643--DESIGNATING MARCH 12, 2026, AS ``DETRANSITION AWARENESS DAY''
https://www.congress.gov/119/crec/2026/03/16/172/47/modified/CREC-2026-03-16-pt1-PgS1057.htm

Marsha Blackburn, Senator from Tennessee
- "gender ideology has resulted in irreparable harm to individuals,
  especially minors"
- "Detransition awareness day" ... "celebrates and commits to
  fostering the biological reality of young men and women"
