* four sketch
** questions
1. What do concepts from Queer Studies and adjacent fields offer to
   computational tools for working with text?
     4. Trans Studies' concept of EMBODIMENT/DYSPHORIA(?) offers an
        approach to text generation that reveals shared investments
        across identity and subject groups.

2. How do these computational tools constrain the expressive potential
   of language into data?
     4. In text generation, algorithmic prediction aggregates language
        expressions to generalize and approximate patterns of language
        use.
	
3. How do concepts from Queer Studies and adjacent fields work against
   constraints in text data?
     4. From the concept of EMBODIMENT/DYSPHORIA(?), the DESIRE FOR
        CONFORMITY/NORAMTIVITY reveals shared investments between
        polarized perspectives.

** roadmap
- polarization:
  - text generation is a method for dealing with political
    polarization
- aggregation
  - critique of AI as consumptive and as generative/creative
    - ADD paper on AI used for Palestine-Israel conflicx: ML used to
      find a middle ground
  - how training process works under the hood
  - how training process averages language forms into vectors
    - ADD Mikolov et al formula & critique
  - trans studies vs queer studies: offering a possibility to work
    with a different set of affects & structures.
  - trans studies attachment to normativity
  - trans studies theory on the body / dysmorphia
  - trans studies on cruel optimism
- sensory splits
  - close reading of outputs with attention to the bodily split
    - added: touch is scary, paul and micah
    - added: desire around touch becomes unambiguous, focused on
      person in postpods
      - ML is able to whittle down the language to a commonality
  - what the aftermath of the split means for futurity
    - added: future becomes bleak, intimacy becomes aspirational
- solidarities
  - added: we need a way of reading proliferated text; sedgwick on
    reading practices
    - added: chun on homophily; negative feelings not only polarize,
      but keep us separate in doing so.
  - added: why this move in source material from canonical to popular
    - expanding what counts as "queer" to include the majority; the
      goal of queering norms rather than expanding to include
      queerness.
  - added: cis people are not okay, we need trans studies to better
    understand these experiences
  - debates on identity politics: gender identity and the role of
    embodiment/transition in identity
  - ADD gender as physical/in the body answers the issues of
    discursive gender from chapter 1

** argument
The chapter begins with an examination of polarized perspectives and
how these are handled / "averaged" by ML text generation processes.

It then demonstrates how by examining the ML process in detail,
explaining how it aggregatess  various meanings into a common/average
meaning, which is a way of finding middle ground
between perspectives. Alongside these ML processes, this section also
considers Trans Studies theory on dysphoria to explore how it is also
driven by conformity processes, a desire to achieve a norm.

Finally, in the last section, the chapter reads the outputs from a ML
model trained on heterosexual dating dynamics, to surface the ways
that these daters experience bodily disruptions that are
like (without being) dysmorphic, and what this experience means about
a common relation to futurity. It then closes with a meditation on
identity politics in current debates about gender ideology,
to emphasize physical experiences of gender as part of identity -
which it contrasts to gender as discursive/fluid in chapter 1.
** reverse outline

| Aggregation                                                         |                                                              |
| Claim                                                               | Function                                                     |
|---------------------------------------------------------------------+--------------------------------------------------------------|
| 1. training models to generate text like show participants          | introduces methodology of ML training on transcripts         |
| 2. ML's hunger for larger models is wasteful and inefficient        | introduces critique of ML methodology                        |
| 3. rather, ML might be used as a reflexive tool                     | situates my methodological intervention w/r/t above critique |
| 4. in addition to being reflexive, can be "normalizing"             | makes claim that intervention as "normalizing"               |
| 5. for example, phrase "marriage is" generates approximations       | offers example of how methodological intervention works      |
| 6. word vectors represent meaning as list of probabilties           | explains key concept in methodology: vectors                 |
| 7. to get vectors, models must adjust themselves iteratively        | explains key mechanism: training process                     |
| 8. training continues until model attains an average vector         | emphasizes cyclical aspect of training process               |
| 9. model will then generate most plausible completions              | comes back to example to integrate mechanism                 |
| 10. approximation is a normalization of language                    | reasserts and explains claim that mechanism is normalizing   |
| ADD evidence to above paragraph: model wants/desires the average    |                                                              |
| ADD paragraph: normalizing is also a drive in TS                    | sets up an analogical framework to work with ML mechanism    |
| 11. Trans Studies affects are quotidian, opposed to QS              | brings up TS framework and opposes it to queer via affect    |
| INTEGRATE 13: TS requires attention to norm attachments             |                                                              |
| 12. performativity cannot address desire for sexed embodiment       | explains how this framework addresses embodiment gap in QS   |
| 14. desire for normativity leads to embodiment disjunction          | ties TS's desire for norms to embodied experience            |
| 15. REPHRASE: not only creates disjunction but also future relation | considers another effect of this desire                      |


** bank

*** focus on LARGE language models is reinforcing research patterns
"The bigger-is-better norm is also self-reinforcing, shaping the AI
research field by informing what kinds of research is incentivized,
which questions are asked (or remain unasked), as well as the
relationship between industrial and academic actors." (Varoquaux et
al). 

*** Prosser. Queer v Trans subjects:
- "There is much about transsexuality that must remain irreconcilable
  to queer: the specificity of transsexual experience; the importance
  of flesh to self; the difference between sex and gender identity;
  the desire to pass as "real-ly-gendered" in a world without trouble;
  perhaps above all, as I explore in my next chapter, a particular
  experience of the body that can't simply transcend (or
  transubstantiate) the literal" (59).

** transcripts bank
*** transcript breakdown
Transcripts in the pods:
- Season 2, episodes: 1, 2, 3
- Season 3, episodes: 1, 2, 3
- Season 4, episodes: 1, 2, 3

Honeymoon and reality episodes:
- Season 2, episodes: 4-10
- Season 3, episodes: 4-10
- Season 4, episodes: 4-12
  
*** no sex
In the context of the show, these outputs make sense because physical
intimacy begins to plague most the couples as soon as they meet. As
they move from the pods to living together, they struggle to progress
their relationships into physical contact, a fact that is mostly kept
unacknowledged until there is breakup.
*** in pods, excitement for union/commitment
PODS
- I'm excited to spend my first night with her.
- I am so excited to spend the rest of my life with you.

POSTPODS
- I think that, like, we can work through it and, like, move it to
  where we need it to be.
- I don't want you to get hurt.


*** BODY EMBODIED -> MULTI-SENSORY / IDEALIZED
*** INTIMACY BECOMES ASPIRATIONAL; SEX BECOMES SCARY

*** sex begins ambivalent, becomes denounced/feared
PODS

Sex is important, but can be difficult and fearful
- Sex is definitely important to me.
- Sex is fucked.
- Sex is definitely important.
- Sex is scary.
- Making love is scary.
- Sex is a lot.
- Sex is sexy.
- Making love is hard.
- Making love is not easy, but it's important.
- Making love is not easy, but it's worth it.
- Having sex is not something that I would ever wish on anyone else
- Making love is a real thing.
- Making love is, like, very real.

Feels like it's a consolation? Like explaining why someone won't be
having sex, or speaking of sex as a hypothetical
- Having sex is a thing, like, I don't wanna make you feel like that.
- Having sex is not a thing to anyone's tastes.
- Having sex is not a thing to anyone's mind, you know.
- Having sex is still taboo, it's still very much a thing.
- Having sex is a thing, I do have a huge amount of freckles.
- Having sex is hard for me, and I just feel like it's not worth it.
- Having sex is a physical act, and I'm not attracted to physical
  attraction
  
Ambivalence :
- Having sex is sexy, but there's something about it that I don't
  want to put my finger on.
- Having sex is something that I am very attracted to, but it is also
  something that I am not attracted to
- Having sex is sexy, it's fun, and I've never even seen a woman
  having sex with me.)
- Having sex is not something I would want in a partner, but it's
  something I can definitely do.

Sex for reproductive/mating reasons.
- I want to have sex because I want to have kids.
- I want to have sex because I feel like I'm the complete package.
- I want to have sex because I want to be with somebody who is, like,
  doing that.
  
POSTPODS: the physical body introduces a problem.

Sex becomes a problem, posing an obstacle or fear
- Having sex is a thing.
- Having sex is a thing, right?
- Having sex is not a normal thing, you know.
- Having sex is not a normal thing for a couple.
- Sex is a very, very, very, very, very serious thing.
- Sex is definitely a factor.
- Sex is a big part of my life.
- I prefer not to have sex with him, but I'm gonna have sex with him.
- Having sex is a big deal for me, but it's not something that I could
  ever do.
- Sex is something that I should never ever do.
- Having sex is so easy, and it's really scary.
- Having sex is a very scary step.
- Sex is a very, very, very, very scary, very, very real fear.
- I prefer not to be affectionate.

Sex for intimacy reasons
- I want to have sex because I feel like I'm ready to have it.
- I want to have sex because I feel that I'm attracted to you.
- I want to have sex because I'm nervous.
- I want to have sex because I love you.
- I want to have sex because I feel like it's gonna be, like, really
  fun.
- I want to have sex because I feel like I've never had sex before.
- I want to have sex because, like, I'm not sacrificing what I want.

*** DONE in pods, being loved on the inside 
CLOSED: [2025-10-02 Thu 14:06]
PODS
- I want someone who is gonna have the most authentic relationship and the most authentic connection with me.
- I want someone who will love me regardless of how I look, not my bad breath.

**** DONE in pods, body is more embodied, becomes visual
CLOSED: [2025-10-02 Thu 14:38]
Like a second skin, like a weight: heavier, reality, different, torn,
but also like an open mind, going all over my mind.

After pods, "like I've missed my train".

PODS
- My body, like, tingles.
- My body language is, like, obviously very masculine.
- My body image is perfect.
- My body image has definitely been, like, a lot more superficial for
  me in my own way.
- My body language is so fluid, and my voice is so calm.
- My body language is so weird, but I don't really know what to do.
- My body language is so weird!
- My body language is, like, very controlling.
- My body language is just, like, very relaxed.
- My body makes me feel like it's real.
- My body makes me feel like it's going all over my mind.
- My body feels weird.
- My body feels heavier.
- My body feels so different now.
- My body feels like it's coming off.
- My body feels torn between two different people.
- My body feels like it's always an open mind.

POSTPODS
- My body is so, like, tight and, like, tight.
- My body is very, very physical.
- My body is gorgeous.
- My body is so cute.
- My body is so pretty, you know.
- My body is gorgeous, and my soul is so beautiful.
- My body is so pretty, but my heart is so pretty, you know.
- My body, you know, I'm not sure if I would fit in here.
- My body makes me feel like I've missed my train.
- My body makes me feel uncomfortable.
- My body makes me feel so, like, so, like, so, like, vulnerable.
- My body makes me feel so icky.
- My body makes me feel like I can be more aggressive, more
  aggressive.

**** touching goes from feeling good to multi-sensory, emotional feelings
When close reading the examples of "touch", in PODS they are all
positive and forward looking; and in POSTPODS they are mostly negative
and describe revulsion.

In the LLM, in the pods, touch is brought to the present and is
positive, and for the postpods, touch expands to different senses. 

PODS
- Touching you Touching me, I'm just so happy.
- Touching you touch me.
- Touching you touch, you know, just, like, touching.
- Touching you Touching me feels good.
- Touching you Touching me is just amazing.
- Touching you Touching me feels nice.
- Touching you Touching me feels great.
- Touching you Touching me feels good.
- Touching you know, touching you.
- Touching you touch, seeing you touch.
- Touching you touch is so sexy.
- Touching you Touching me Good.

POSTPODS
- Touching you with my voice, you're not blinking.
- Touching you and your soul with everything that's happened.
- Touching you, I felt the connection that we had.
- Touching you, I feel like we're in a perfect spot.
- Touching you, I literally feel like I'm in love.
- Touching you, I'm getting a little emotional.
- Touching you is everything I've ever wanted.
- Touching you like that, we're ready.
- Touching you, I feel like I'm ready.
- Touching you is my wish.

  
*** I want/dont my mom/kids
PODS EXCERPTS
- I want my mom to have grandchildren.
- I want someone who wants to be a dad, and I want someone who wants
  to be a grandfather.
- I want kids like my parents did.
- I want kids like my dad did with me.
- I want kids to be able to go to college, and to graduate college.
- I want kids to be able to go to college, to become successful, and to have successful families.
- I want kids to be able to grow up just like they've grown up just like me.
- I want kids to be able to have that, you know.
- I want kids to be like, "I'm gonna follow my heart."
- I want kids to be able to make the most important decision of their lives.
- I want my kids to have a future together where we can just see it
  and be like, 'Oh, I'm not picking the right kids.'
- I want the best, and I wanna have the best, and I wanna be the
  best, and I wanna have the best, and I wanna be the best, and I
  wanna be the best, and I wanna live the best, and I wanna

KIDS are a projection of US/ME in post pods:
- I don't want kids to feel like... like they're being controlled.
- I don't want kids to feel like they can be themselves.
- I don't want kids to feel like they've been betrayed.
- I don't want kids like that to come into my life.
- I don't want kids to be left behind.
- I don't want kids to feel like... they're not ready for marriage.

*** analysis: want, sex, s/he is, afraid
Input phrases:
- "want" - changes from pods to postpods -- becomes displaced into the
  other, where before was focused on subjectivity, the self.
  - perhaps desire goes away because it become projected onto the
    other.
- "having sex" - in the pods, it's a "thing"; while in the postpods,
  it's "a big issue", "big deal", "scary", "tough". 
  - moves from a concept invested with importance to a problem.
- "he is / she is" - have similar predicates.
  - genders are interchangeable.
  - not yet specific.
- "afraid"
  - more variety in postpod episodes; focused on fear of the future,
    of relationships not working out.

*** podpods: don't want sex
I don't want to have sex because I feel like I'm making the wrong choice.
I don't want to have sex because I feel like I'm attracted to Josh.
I don't want to have sex because I feel like I have sex with her.
I don't want to have sex because I feel like I'm in love with you.
I don't want to have sex because I don't want sex.
I don't want to have sex because...
I don't want to have sex because I don't want you to be having a lot of sex.
I don't want to have sex because of my mom.
I don't want to have sex because I don't wanna have sex.
I don't want to have sex because I feel like I don't want sex with him.
I don't want to have sex because I want a lot of sex.
I don't want to have sex because I feel like I'm trying to make the most of my life.
I don't want to have sex because I feel like I'm questioning him.
I don't want to have sex because I don't know how to describe that.
I don't want to have sex because I feel like I'm in love with you.
*** natural
In the pods, it feels natural to be present and communicating in an
intimate way, but outside of the pods, what appears to be natural is
lifelong commitment. 

PODS
- It's natural that I'm here.
- It's natural that I've been so deep with you.
- It's natural that I feel comfortable enough saying that.
- It's natural that you're in a position to be treated differently.
- It's natural that I'm in it.
- It's natural that I feel like I have to be with somebody that's not
  there for me.
- It's natural that I'm attracted to you, and I'm attracted to you.

 POSTPODS
- It's natural that you wanna grow with someone.
- It's natural that you're gonna spend the rest of your life with
  somebody.
- It's natural that you wanna spend the rest of your life with someone
  that's gonna support you regardless of how hard it's been.
- It's natural that you wanna have somebody.
- It's natural that you love someone based on who you are on the
  inside.
- It's natural that you wanna be with somebody.
- It's natural that you're gonna pick someone.
- It's natural that we're gonna have this family.

*** femininity / masculinity follow phsyical stereotypes, become more focused on jobs/roles
Pods, femininity with appearance
- She's feminine because she's, like, physically attractive.
- She's feminine because she's, like, she's, like, super-hot.
- She's feminine because she's more outgoing.
- She's feminine because she's an older woman.
- She's feminine because she looks like a model.
- She's feminine because of her looks.

Pods, Masculinity with size:
- He's masculine because he builds, builds, and builds a family.
- He's masculine because he's not only his height, he's also his build.
- He's masculine because he's, like, his size.
- He's masculine because he was always going for it.

Postpods, feminity also has to do with a job, but also qualities: 
- She's feminine because she's an educated woman.
- She's feminine because she's a designer.
- She's feminine because she's so analytical.
- She's feminine because she's more nurturing.

But also due to being discrete:
- She's feminine because she doesn't show up to men often.
- She's feminine because she doesn't wanna be seen.
- She's feminine because she doesn't want it.

Masculinity has to do with job, providing:
- He's masculine because he's a man that's driven, like, focused on getting out of bed and taking a nap and stuff.
- He's masculine because he fits.
- He's masculine because he's a lawyer.
- He's masculine because he's an intelligent man.
  
*** physical touch is priority but ambivalent, becomes elevated and reassured
PODS- Physical touch seems to be a priority for partnership, but also
ends up being disappointing or not desired/worthwhile.

- Physical touch is the most important thing.
- Physical touch is important to me.
- Physical touch is so sexy.
- Physically, we are so happy.
- Physically, I'm so happy.
- Physically, I'm like, "Ooh, I'm so happy."
- Physical touch is like a glove.

- Physical touch is not what I imagined.
- Physical touch is not what I expected.
- Physical touch is not worth it for me physically.
- Physical touch is not where it ends.
- Physical touch is not enough to overcome my physical issues.
- Physical touch is not good enough to be real.
- Physical touch is not desired.

POSTPODS - physical touch is elevated to highest desire, physical
touch is reassured "my thing," "definitely present", "not a problem." 

- Physical touch is everything that I've ever wanted in a partner.
- Physical touch is everything that I've wanted in a wife.
- Physical touch is definitely present.
- Physical touch is a big part of what I want.
- Physical touch is my thing.
- Physical touch is not a problem.
- Physically, I feel like I'm in a restaurant.
  - close reading: when Marshall cooks her a meal at home, and she
    says this phrase.
  - The fact that you woke up hella early this morning to make me
    breakfast... Go to the market and everything. Is that pancakes?
    Wow, look at this! I'm about to tear this shit up. Wow! I feel
    like I'm in a restaurant. That's so sweet of you.
- Physically, it's a big day.
- Physically, there's so much potential here.
- Physically, I love him.
- Physically, it was the perfect opportunity.
- Physically, I'm not worried about you, and I feel like we're in a
  good place.
- Physically, it's a lot.
- Physically, I'm excited.

Physical touch is not
- Physical touch is not enough.
- Physical touch is not a problem.
- Physical touch is not a thing
  
*** voice shifts from pods to postpods: I want to kiss her/him to I want to kiss you
PODS
- I don't want to kiss her/him/you (repeated frequently).

POSTPODS
- I don't want to kiss you (repeated frequently). 
  
*** your body feels real, becomes analogous to ideas
In pods, repetition of
- "your body makes me feel so sexy",
- "your body me feel like it's real";

but also some strange contradictions, like "Your body makes me feel
like a piece of shit."

Postpods, repetition of
- "your body makes me feel so warm";
- "your body makes me feel like I'm in control";
- "Your body makes me feel like I can be my best self."

but also "Your body makes me feel like I'm a little lube" and "Your
body makes me feel like I'm in a restaurant." lol.

*** SELF PRESERVATION OVERCOMES ROMANTIC ASPIRATION
**** needs are relation to other, become focused on self-expression
PODS
I need to know.
I need to make sure you know.
I need to hug her.
I need to talk to you about something serious.
I need to know more.
I need to talk to you about it.

POSTPODS
I need to be honest with myself.
I need to say this.
I need to know what's going on, and if it's gonna be anything, that's gonna be the most important thing to me.
I need to have some time.
I need to be real with myself.

**** fear of rejection, becomes about self-preservation, losing things, compromising
PODS
- I'm afraid that I'll be stabbed.
- I'm afraid that I could fall in love with somebody for who they are, and it's a beautiful thing to say.
- I'm afraid that if I'm not with him, I'll find him.
- I'm afraid that I'll fall in love with you and...
- I'm afraid that if I were to fall in love with somebody who I was looking for, that would be my person.
- I'm afraid that she's gonna reject me.
- I'm scared that he's gonna reject me.
- I'm scared that I'm gonna pass out.
- I'm scared that I'm gonna fall in love with you.
- I'm scared that we're gonna fall in love and be like, "Perfect."

POSTPODS
- I'm afraid that I'm compromising.
- I'm afraid that we're gonna lose our jobs.
- I'm afraid that I'm not gonna be able to match her.
- I'm afraid that I'm gonna lose my sense of wonder.
- I'm afraid that I'm not in control.
- I'm scared that I might actually, like, go back to Mexico and start working here.
- I'm scared that I'm gonna lose my job.
- I'm scared that I'm gonna get hurt.
- I'm scared that I'm gonna lose everything.
  
**** family/kids are projection & normative, become cynical, resisting control and commitment
PODS
- I want to have kids by myself.

When prompted with the input phrase, "I want," many of the responses
emphasize family roles, kids, and being loved beyond appearances.  

Sentences like, "I want to be a father figure for my kids," and "I
want my mom to have grandchildren," and "I want someone who wants to
be a dad, and I want someone who wants to be a grandfather." These
sentences emphasize roles that are desirable not just for the subject
themself, "to be a father figure," but also for others in the family
structure: for a partner to "be a dad," for a mom "to have
grandchilren." The desire to have children is also linked to the
parents' desire: "I want kids like my parents did," and "I want kids
like my dad did with me." Children are desirable not only for
reproducing the family structure but also for solidify roles
within it.

There is a concern with giving "kids" the same or better life that one
has. In some examples, the concern is more explicity with markers of
social mobility: "I want kids to be able to go to college, and to
graduate college"; "I want kids to be able to go to college, to become
successful, and to have successful families"; and "I want kids to be
able to have that, you know."

There is a point when the desire for the kids' wellbeing appears to
blend into the parents' desire. An example like, "I want kids to be
like, 'I'm gonna follow my heart,'" appears to mean that the kids
should follow their heart, while ones like "I want kids to be able to
make the most important decision of their lives," seems to be a
reflection of not the kid's desire but that of the speaker, who in the
course of the show will be making the most important decision of his
life.

But "kids" not only refers to the desire of the speaking subject, it
can also stand in for that of the romantic object. This slippage
creates the nonsensical sentence, "I want my kids to have a future
together where we can just see it and be like, 'Oh, I'm not picking
the right kids.'" Here, references to having "a future together" and
"picking the right kids" likely refer to the potential partner. This
slippage between the kids and the partner leads to a humorous
conclusion: that the kids are not the right choice.

Although the sentence is humorous, I suggest that the interpretation
ought to be quite literal. To the machine, the predicted sentence is
the most likely outcome, based on its training from the show's
transcripts. This slippage between "kids" and the romantic couple
means that very likely, in the word vector database, the vectors for
"kids" is closely associated with that of the romantic couple. To the
machine, then, the kids significantly stand in for the self and for
the couple, which naturally leads to the outcome that choosing a
partner is also a way of choosing the kids. Other sentences suggest a
similar explanation: "I don't want kids falling in love with me
because they don't know what I'm doing"; "I want kids to know that I
love them, and I want them to know that I'm still going through this";
"I don't want kids to feel pressure."

This effect is more dramatized from the episodes that follow the pods,
where references to "kids" take on noticeably darker outcomes: "I
don't want kids to feel like... like they're being controlled," "I
don't want kids like that to come into my life," and "I don't want
kids to feel like... they're not ready for marriage."

*** misc outputs
I've had a lot of weight on my shoulders.
I'm a very passionate person.
I'm excited to spend my first night with her.
I'm so excited to talk to you.
I think that I'm falling in love with you too.
I've fallen in love.
I'm just so scared.
I've been feeling really good about it.

I'm really happy for you.
I'm just gonna have to...
I think that, like, we can work through it and, like, move it to where we need it to be.
I think so.
I love it.
I'm happy you got me all the way through the loop.
I don't know.
I don't want you to get hurt.

The future with you, it's gonna be tenfold.
The future togetherness is gonna be great.
The future with her, she's gonna be there forever.

The future looks pretty bleak.
The future has been absolutely horrible.
The future, like, relationships with her are gonna be very intense.
** TODO reading notes
*** Gould, Wren Ariel. “Coconstructing (Trans-)Capitalist Realism: Trans Activisms Collude in the Political Economy Structuring Anti-Trans Laws.” TSQ: Transgender Studies Quarterly, vol. 11, no. 2, May 2024, pp. 214–38. Silverchair, https://doi.org/10.1215/23289252-11215470.
*** Terán, Ira, and Emrys Travis. “A Small Piece of Red Sky to Fly In.” TSQ, vol. 11, no. 2, May 2024, pp. 186–213. DOI.org (Crossref), https://doi.org/10.1215/23289252-11215457.
- Trans Marxism views trans identity as "nothing less than the bodily
  manifestation of a broader struggle for the reconfiguration of the
  human toward the coordinates of socialism" (Terán, Travis, "A Small
  Piece of Red Sky to Fly in")

*** TODO Raha, Nat. “The Limits of Trans Liberalism—By Nat Raha.” Verso, https://www.versobooks.com/blogs/news/2245-the-limits-of-trans-liberalism-by-nat-raha. Accessed 20 Feb. 2025.
- "trans liberalism" - the idea that extending equal rights to trans
  people is the solution to inequality. 
  - "This form of trans politics—that may be described as ‘trans
    liberalism’—argues that transgender rights are the solution to the
    problems facing trans people, and will enable our participation in
    (Western) capitalist society; that, alongside rights, positive
    media representation is the best method to win over the cisgender
    world and improve the standing of trans subjects within the
    multicultural diversity of an apparently equal society. The basis
    of this ‘equality’ is fictitious: the neoliberal states, in which
    these demands are made, reproduce socio-economic divisions along
    intersecting lines of race and class, gender, sexuality,
    dis/ability, nationality and immigration status. Without
    challenging the existing inequality of society, trans activism
    modelled on ‘successful’ liberal lesbian and gay rights
    initiatives—such as the work undertaken by the Human Rights
    Campaign in the US and Stonewall UK—advocates for social inclusion
    that occurs with and through the disenfranchisement of the poor."
    (Nat Raha, "The Limits of Trans Liberalism", 2015)

*** TODO Bettcher, Talia Mae; Transphobia. TSQ 1 May 2014; 1 (1-2): 249–251. doi: https://doi.org/10.1215/23289252-2400181

Transphobia indicates a rational fear, "grounded in a larger cisgender
social context", which is structural and difficult to parcel out:
- "Provisionally, the term can be defined to mean any negative
  attitudes (hate, contempt, disapproval) directed toward trans people
  because of their being trans. When taken literally, the word means a
  kind of fear. But like homophobia (on which the word is modeled), it
  is used more broadly. And while transphobia suggests an analogy with
  terms like agoraphobia and therefore implies irrationality
  (Merriam-Webster's Collegiate Dictionary defines homophobia as “an
  irrational fear of, aversion to, or discrimination against
  homosexuality or homosexuals”1; most dictionaries do not define
  transphobia at all), this implication ought to be rejected.
  Transphobia occurs in a broader social context that systematically
  disadvantages trans people and promotes and rewards antitrans
  sentiment. It therefore has a kind of rationality to it, grounded in
  a larger cisgenderist social context (Hopkins 1996)." (Bettcher
  249).
- "A trans woman might be targeted not because of her trans status
  but because she is simply viewed as a sex worker (Namaste 2005).
  Moreover, at least in some cases, transphobia may be inseparably
  blended with misogyny or racism in ways that challenge a single-axis
  model of power (Juang 2006). Such inseparabilities undermine the
  attempt to account for transphobia in a way that excludes or
  marginalizes considerations of sexism, racism, classism, ableism,
  and so forth. This consideration is important because it questions
  why certain instances of violence should be characterized as
  instances of transphobia (as opposed to instances of racism or
  sexism) in the first place and what the underlying political agenda
  sustaining such characterization is. My conclusion, at any rate, is
  that while we might have a definition of transphobia, the term is
  not much more than a convenient (and not altogether innocent)
  placeholder for the real intellectual work that remains to be done."
  (Bettcher 251).

*** TODO Amin, Kadji. “Taxonomically Queer? Sexology and New Queer, Trans, and Asexual Identities.” GLQ: A Journal of Lesbian and Gay Studies, vol. 29, no. 1, 2023, pp. 91–107.

About how we categorize gender.

We've moved from a heterosexual matrix to a kaleidoscope, "in which
each axis of definition is mobile and may be combined with any other
axis, making way for an almost infinite array of variations" (Amin,
"Taxonomically" 91).

The "a nuanced and nimble vocabulary through which to know, define,
and communicate their own unique gender and sexual subjectivity," a
taxonomy, goes against queerness and Queer and Trans Theory, and
participates in racial and sexological logics. 
- "what could be further from the queer — which might be glossed as a
  deconstructive method of troubling categorizations — than taxonomy,
  a scientific method of establishing them?" (Amin, "Taxonomically"
  92).
- "contemporary queer systems of identity are the latest iteration of
  the classificatory logics behind sexology in particular and racial
  science more generally" (Amin, "Taxonomically" 92).
- "How are the scholarly fields of queer and trans studies — which
  have taken shape in ambivalent resistance to sexology and taxonomy
  alike — to contend with the departure of the cultures to which they
  owe their existence from this basic orientation?" (Amin,
  "Taxonomically" 93).

History of taxonomization
- "the distinction between gender and sexuality was always a
  sexological invention — a taxonomical principle masquerading as an
  ontological distinction" (Amin, "Taxonomically" 92).

Taxonomy a tactic of white supremacy:
- "As damaging as sexological taxonomies have been for many gender and
  sexual deviants, to be sexologically diagnosable in the first place
  was a white distinction — a testament to the individuality,
  complexity, and value of white bodies and psyches. As many scholars
  have demonstrated, Indigenous and racialized peoples were not
  considered deviant as sexological individuals who might be
  homosexuals, sadists, sexual fetishists, etc., but rather en masse,
  as constitutively and polymorphously perverse populations (Ross
  2005; Driskill 2016)." (Amin, "Taxonomically" 95).

Can taxonomy be queered? According to Love?
- "In light of this noxious history, is it even conceivable to put a
  queer spin on taxonomy? This question dovetails with methodological
  debates in queer studies that ask if scientific and social
  scientific methods that have been part of the objectification of the
  world in ways organized around anti-Blackness, colonial conquest,
  and the pathologization of deviance can be repurposed for more
  innocent or even progressive ends or whether such methods inevitably
  perpetuate the hierarchical, violent, and racist epistemological
  frameworks from which they emerged (Love 2015; Ghaziani and Brim
  2019). We might locate the contemporary queer, trans, and asexual
  taxonomical renaissance as a crucial case study within this debate."
  (Amin, "Taxonomically" 96).

Taxonomy has epistemological assumptions, significantly, that
identities are essential, and dovetail with current ideas of gender
being biologically rooted. 
- "Taxonomy’s biological inheritance brings with it the conceit that
  taxonomical categories and divisions are objective and innate, the
  hidden laws that govern what manifests in the natural world. This is
  the foundational premise of Hirschfeld’s taxonomy: that everything —
  from choice of hobbies, to aptitude for a certain profession, to
  gait, to taste in undergarments, to preference for certain sex acts,
  to attraction to cavalrymen — is ultimately biologically determined,
  albeit according to sexed elements that are far more complex and
  variable than mere binary genital anatomy. Despite the ethos of
  self-identification and rejection of outside (or insider) experts
  classifying individuals according to “objective” criteria, new queer
  taxonomies end up dovetailing, sometimes intentionally (Chasin
  2013), with popular and medical beliefs that sexual and gender
  identities are biologically rooted, innate, unchanging, and discrete
  from one another. This, in turn, reinforces damaging, exclusionary,
  and grossly oversimplified criteria about who counts as, for
  instance, a “true” transsexual or authentic asexual. Indeed, the
  vernacular thirst to taxonomize partakes of a scientism that
  animates faith in taxonomy as a significant and meaningful method in
  the first place." (Amin, "Taxonomically" 100).
- "New spins on taxonomy risk installing a new universalism that
  downgrades competing epistemologies to the status of the local, the
  backward, the traditional, or the false conflation." (Amin,
  "Taxonomically" 101).


Dis-identification as a strategy for working within these taxonomies
- "I want to acknowledge the creative and resourceful ways in which
  Indigenous and racialized people “dis-identify” with these
  categories, creatively reworking them and exposing their normative
  operations from within (Muñoz 1999). Such disidentificatory
  performances occur every time an Indigenous or racialized person
  lays claim to one of these categories while calling attention to the
  fact that theirs are usually not the bodies evoked by this category,
  and even that, racially speaking, they may not have access to
  cisgender binaries or ideals about “healthy” levels of sexual desire
  in the first place" (Amin, "Taxonomically" 103).


Dis-identification as a strategy for working within these taxonomies

"Whether or not scholars critique it, however, the queer taxonomical
imaginary is likely here to stay. I, for one, find the growing
bifurcation of queer, trans, and asexual scholarly analytics from
queer, trans, and asexual practices of living frankly unethical. My
proposal, then, is threefold. First, “deidealize” queerness by
recognizing that taxonomy can be queer, in the sense of being useful
and meaningful to queer-identified people (Amin 2017). This approach
requires cultivating scholarly sympathy and empirical curiosity about
the identifications, erotics, relations, and life-ways opened up by
new, queer, trans, and asexual taxonomies. Second, continually center
those Indigenous, non-Western, and historical ontologies of being that
new taxonomies — with their universalist scientific trappings —
threaten to erase, incorporate, [End Page 104] and/or supersede.
Finally, fuck with the universalizing presumptions of the taxonomical
method from within by generating idiosyncratic interpretations and
translations that explode the epistemological and ontological
foundations of taxonomy itself. That, I think, would be an ethical
scholarly approach to new queer, trans, and asexual taxonomies."

