* secondary sources, /orlando/
** Benzel, Kathryn N.
"Reading readers in Virginia Woolf's Orlando: A Biography." *Style*,
Summer 1994, p. 169+. *Academic OneFile*,
go.galegroup.com.ezproxy.gc.cuny.edu/ps/i.do?p=AONE\&sw=w\&u=cuny\_gradctr\&v=2.1\&it=r\&id=GALE%7CA16528204\&asid=f0799f9a91ad99c3225197789ee9cbed.

Benzel application to the space break: Benzel argues that the narrator
writes in a way that requires the reader’s input. There are explicit
moments, like the space break. Here, the narrator is being clear about
the work of the author and of the reader. It is up to the author to
write, and the reader to read. Readers are part of the creation of
meaning. They incorporate their own creative powers, like the writer.
The reader works like the writer to create meaning by what is there,
or isn’t there. Which is what the space break shows us. So this is one
level of application between reader and writer. There’s another
application on a thematic level for Orlando’s character. We cannot
truly know Orlando’s character, we only know what the biographer tells
us, and the biographer is also limited by her perspective. A lot of
this is guesswork. Speculation, based off of what isn’t there. The
blank space therefore also represents what we do not get of Orlando.
The absence of evidence, which we have to fill in.

Benzel identifies the collaborative nature of reading that Woolf
requires by asking her readers to recognize the "plurality in the text
through his/her own multilevel reading" In Orlando: A Biography,
Virginia Woolf experiments with both biographical and fictional
conventions in order to engage the readers in the creation of the
text's meaning. In Orlando Woolf develops a narrative environment that
encourages the writer and reader to share the aesthetic experience in
this text. This type of reading posits relational and alternative ways
to discovering about the world in the text; readers are asked to
"refresh and exercise \[their\] own creative powers" in order "to make
use of all that the novelist—the great artist—gives \[them\]." By
analyzing this cooperative interaction, the text is revealed as a
territory, often a narrative playground, in which reader creates and
recreates an aesthetics of reading.

“The cooperative process between reader and writer in Orlando is
analogous to the characterization of Orlando: like the biographer
struggling to characterize the subject, we as readers struggle to
create our place in this text. The writer, the narrator-biographer,
and reader must work to overcome the constraints of narrative
conventions in order to construct a "real self," a self that creates a
reality in and of the text. From this relationship between writer and
reader, a Woolfian aesthetic emerges, an aesthetic that is
collaborative, contextual, and compelling. “ “The shared aesthetic
experience, I believe, motivates Woolf in Orlando as she attempts to
define and redefine the reader's role as participant creating the
biographical characterization of Orlando.”

“Rabinowitz's and Phelan's rhetorical approaches to audience clarify
Woolf's notion of the reader's double perspective as the reader
experiences both the mimetic illusion of the story and its manner of
presentation. By engaging with the text on these two levels, the
reader experiences reading as a creative activity, an aesthetic
experience in the context of this particular text. While we read, we
seek out textual cues that reinforce the mimetic illusion, but the
very act of seeking out such cues focuses our synthetic reading. The
consequent tension between the narrative reader (looking for
representation) and the authorial reader (recognizing the text's
discourse) enriches the aesthetic experience by engaging the reader
with the text's multiplicity. This aesthetic is an act of
interpretation in the sense of Roland Barthes's notion of
interpretation: "To interpret a text is . . . to appreciate what
plural constitutes it" (5; Barthes's emphasis). By concentrating our
attentions both on the character of Orlando and on the construction of
Orlando's character, Woolf creates a double-visioned reader, a reader
who realizes the plurality in the text through his/her own multilevel
reading.”

“The distance between the narrative and authorial readings allows the
reader to play with the characterization of Orlando's sexuality in
order to reconstruct an image of multiplicity that works within the
text.”

** Berman, J.   
“Is the Trans in Transnational the Trans in Transgender?"
*Modernism/modernity*, vol. 24 no. 2, 2017, pp. 217-244. *Project
MUSE*,
[doi:10.1353/mod.2017.0019](http://doi.org/10.1353/mod.2017.0019)

“Woolf's novel, like other twentieth-century narratives, demands to be
read as what I call a "trans" text, one that challenges prevailing
assumptions about national belonging and scenes of reading, asking to
be situated in the context of transnational modernism or
twentieth-century "world literature" at the same time as it raises the
question of gender and sexual identity as a constitutive dimension of
those critical
categories.[6](https://muse-jhu-edu.ezproxy.gc.cuny.edu/article/658469#f6)
This kind of a "trans" text challenges the normative dimensions of
regimes of nationality and disrupts the systems of embodied identity
that undergird them. It pushes us to recognize that any discussion of
transnational or world literature must also attend to the assumptions
of embodiment and gender identity that are attached to the concept of
the nation” (218).

“Reading the transnational situation as also intrinsically transgender
disrupts the determinative power of both the sexed body and its "home"
geography, thereby also challenging the Orientalism of the novel's
Turkish episodes and the seeming solidity of categories of gender
identity once Orlando arrives back on English soil” (218).

“Under this rubric, a transnational *and* transgender approach to
*Orlando* would not simply juxtapose male and female Orlando, or
Orlando in Turkey with Orlando returned to England, but would rather
explore the challenge to embodied normative nationality that emerges
throughout the middle sections of the book, making national belonging
both what Orlando longs for from the hills of Turkey and what her
transformative experience in Turkey forever undoes. Throughout the
novel, as the narrator claims, Orlando's sex may often be the "very
opposite" from "what … is above" (139). From its troubling first
pages, this transgendered status also lies at the heart of the novel's
critique of empire, in which bodies must be identifiably marked,
categorized, and placed in hierarchies. Reading this novel under the
rubric of the oppositional prefix "trans" thus highlights the extent
to which Orlando's sex change in Turkey is also—and always—a challenge
to the embodiment of nationality and empire, and invites us to
recognize the importance of this confluence in other texts, both from
the early decades of the twentieth century and beyond” (221).

“In much contemporary transgender theory, the prefix "trans" has come
to stand not for gender or sexual identities that have moved from one
side of a binary field to the other, but rather for "anything that
disrupts, denaturalizes, rearticulates and makes visible" the links we
assume to exist between a sexual body and the social roles it is
expected to play” (222).

“Having no category for a transgender subject, the nation must
domesticate Orlando by naming her as immutably female, and assigning
her the diminished rights and opportunities of women in late-Victorian
England: "'The lawsuits are settled. … My sex … is pronounced
indisputably, and beyond the shadow of a doubt. … Female. The estates
which are now desequestrated in perpetuity descend and are tailed and
entailed upon the heirs male of my body" (*Orlando*, 186–87).
Orlando's ultimate loss, as a woman, of the right to inherit
demonstrates not only women's political and economic poverty within
the Victorian gender system, but also the degree to which the state
depends on this binary system as a basis for assigning citizenship
roles, policing its borders, and determining who has legal standing to
inherit, hold property, or sue for redress. … In other words, despite
Orlando's seeming reinscription into national norms of femininity,
attending to her trans status shows how, in the novel, a transgender
identity produces a kind of internal exile and generates transnational
critique” (227).

“Indeed, personhood, as it is understood in post-Enlightenment Western
legal systems and in such documents as the United Nations' Universal
Declaration of Human Rights (1948), does not mark the "human as such."
Rather, it constructs "a person as a member of a people or nation—a
particular kind of human activated as a legal and moral unit"
(Slaughter, *Human Rights, Inc*., 58). The "person" therefore becomes
embodied as a normative entity with specific rights, responsibilities,
and duties under existing social, cultural, moral, and juridical
systems and remains inscribed within—and often subjected to—existing
hierarchies of gender, power, and value (Spade,*Normal Life*, 30, 37).
By implication, the non-conforming "human" risks losing access to
"human rights."” (229-230).

“By ruminating on the potential disconnection between clothing and
embodiment, Woolf not only mobilizes a familiar Orientalist trope but
also and perhaps more importantly demonstrates that we never have
"unmediated access" to "the materiality of the body" nor do we ever
know it with certainty (Salamon, *Assuming a Body*, 1). As in many
other moments in Woolf's text, this scene shows us that lurking
beneath every clothed, draped, cloaked, hatted, or turbaned
body—whether in East or West—lies the perpetual disjuncture between
embodiment and the biopolitics of gendered, and racialized, national
identity… ). While the gender-neutral Turkish trousers had
"distract[ed] her" from the question of her sex, English garb
insists upon it, and demands that she change clothes as she vacillates
among gender identities, slipping in and out of womanhood during the
succeeding pages (113)” (234).

“Understanding the variety of relationships between these terms
prevents us from mistakenly viewing the transnational as a purely
spatial or political attitude that can be put on or taken off without
affecting other more "core" aspects of identity or, on the other hand,
understanding transgender identity as a personal or biological matter,
essential and separate from the historical and political concerns of
nationality, identity, or allegiance… I would argue that Woolf reaches
for Orientalist tropes in /Orlando/ not because of her fantasies about
Turkey or the gypsies (which she may well have harbored) but because
she rightly recognized that English civic discourses about gender and
nationality allowed no room for narratives of transgression or change
on her home turf” (235).

** Burns, Christy L.   
“Re-Dressing Feminist Identities: Tensions between Essential and
Constructed Selves in Virginia Woolf's Orlando.” *Twentieth Century
Literature*, vol. 40, no. 3, 1994, pp. 342–364. *JSTOR*,
www.jstor.org/stable/441560.

“As desire for identification draws Woolf toward the genre of
biographical fiction, the need for differentiation following upon such
a mimetic project propels her back into parody.2 If the text is "true
to" Sackville-West's personal history, the novel is still quite
unfaithful to the genre of biography. How can one be both faithful to
facts and unfaithful and tell more of the truth without exactly
telling it the same?” (342).

“In her novel truth is destabilized and turns into parody through an
emphasis on period fashions, cross-dressing, and undressing of
"essential"” (343).

“This question of whether some innate human essence can surmount
historical effects or whether the only "essence" we know as
personality is fully shaped by the world around one-this problem is
comically re-figured by Woolf as the question of whether the clothes
"make the (wo)man."” (343).

“I do not aim to treat Orlando as a mirror to any single vision of
contemporary feminism, so much as to mark it as a historically
significant text that informatively examines the tensions between
notions of essential personal identity and contextually re-defined
subjectivity, tensions that are replicated in contemporary debates
between essentialist and post-structuralist feminists” (344).

Parodying different kinds of biography: Lytton Strachey’s
pschoanalytic method (influenced by Freud) and Leslie Stephen’s
essentialist method (influenced by the Positivists). Questions of
social constructedness versus essential selfhood. “Orlando was the
novel that allowed her to chart the tension between these two
contradictory beliefs” (345).

“The questioning of identity in Orlando raises issues that are of
returning importance to feminism. How much of the self, Woolf asks, is
unchangeably and essentially our own? How solid a space does one have
for resistance to social demands for conformity? Does the "spirit of
an age" weigh upon the sexes differently? And how does one's
adaptation or resistance to society affect one's writing? If such
questions are implicitly structuring the narrative drama of Orlando,
they are explicitly posed in Woolf's feminist essays, most notably in
A Room Of One’s Own” (346).

“Orlando's sex change parodies the philosophical search for bare,
naked, essential truths. And it is no coincidence that a parodic text
will unravel any fantasy of pure and perfect mimetic reference… In
this scene such classic motifs as unveiling and nakedness are
re-organized around questions of sexuality, and what is "revealed" or
"unveiled," the "truth" of Orlando's sex-that he is a she-points only
to the essential instability of essence, the reversibility inscribed
within the “truth”. What is essential here is to be without an
essence. What is revealed is the reversibility of sex” (350).

“The biographer struggles to write the "naked truth" about Orlando,
but the revelation of his sex change tells us little. Likewise,
Orlando later gets embroiled in the struggle to "say what one means
and leave it." What she finds in trying to abandon metaphor, however,
is that simple statements get no closer to the truth” (352).

“I do believe that the form of parody that Butler describes-one that
presses toward heterogeneous mixtures of the norm and the
contra-normal-carries with it the politics she describes. Her model
offers parody and cross-dressing, in particular, as acts that cross
boundaries and allow one to perform subjectivity in a dialogue with
social expectations for conformity-to resist without fully breaking
with, to remain politically active within the system without
conforming to it” (356).

“I point toward this close relation between "the self" and biography
that constructs the self through language in order to emphasize the
ways in which Orlando's surviving question-that of who Orlando is-and
Woolf's genre, parodic biography, are integrally related. I would like
to suggest through a reading of Orlando that notions of the self are
intricately linked to writing for Woolf, and that the essence of a
word functions just like the essence of a person, clothed in social
conventions and full of indeterminacy’ (357).

** Channing, Jill.
"Magical realism and gender variability in Orlando." *Virginia Woolf
Miscellany*, no. 67, 2005, p. 11+. *Literature Resource Center*,
go.galegroup.com.ezproxy.gc.cuny.edu/ps/i.do?p=GLS\&sw=w\&u=cuny\_gradctr\&v=2.1\&it=r\&id=GALE%7CA297555320\&asid=6240f6f50a48d8c46887b718c4bda7a8.

“Woolf would probably not have known of the term "magical realism";
however, like all magical realist novels, Orlando disrupts modern
realist narrative expectations, destabilizes normative oppositions,
blurs and transgresses boundaries, is an act of subversion, and most
importantly, I believe, creates a space for diversity. In Orlando, not
only is Woolf writing a prototype of a magical realist text that is
subversive and creates a space for diversity, sexual diversity
specifically, she is also using this genre to critique British
cultural views of sexuality” (11).

“While Orlando is subversive in form and content, Woolf would not have
been able to overtly express her ideas about gender and sexuality
except through her experimental use of magical realism. After seeing
works of authors such as James Joyce and D. H. Lawrence being tried
for obscenity and consequently being censored, Woolf probably
anticipated that she should disguise her representations of the
fluidity of sexuality in order to protect her work from censorship”
(11).

“The touchstone of magical realist work is the "irreducible
element”... “The central magical event in Orlando--although not the
only magical irreducible event--is Orlando's changing from a man into
a woman. There is no explanation offered for the sex change, and
Orlando does not appear to be concerned by the event” (11-12).

“Another significant characteristic of magical realism, according to
Faris, is "historical anchoring" often expressed by "a character
\[who\] experiences historical forces bodily" (Ordinary 16). The
spirit of the age, an irreducible element itself, has power over
Orlando that she sometimes resists but never can completely ignore”
(12). “Presenting societal forces as "the spirit of the age" allows
Woolf to critique compulsory heterosexuality by presenting it as a
magical force that gives Orlando no choice” (12).

“The third element of magical realism outlined by Faris is the
presence of unsettling doubts. Faris explains it thus: "Before
categorizing the irreducible element as irreducible, the reader may
hesitate between two contradictory understandings of events, and hence
experience some unsettling doubts" (17). Most of these unsettling
doubts are caused by the reader's confrontation with magic, and the
biographer provides no definite explanations for these magical
occurrences. However, the narrator offers some possibilities when s/he
cannot explain something that has happened” (12).

“Hesitations could also be caused by the fourth characteristic Faris
uses to define magical realism, which is the "near-merging of two
realms" (Ordinary 21). Orlando blurs the world as experienced by men
and women. These two realms come close to merging since although
Orlando changes sexes, s/he remained "fundamentally the same" (237)...
Her merging and reemerging from the worlds as experienced by men and
women allows Orlando to critique especially how men stereotypically
view women. Orlando finds that women have desires just as men and that
they, contrary to what men think, are capable of feeling for their own
sex” (12-13).

“Magical realism allows Woolf to transcend absolutes, binary
oppositions, and genre-defined boundaries of literature as well as
socially-defined boundaries of sexuality to create a character who is
not simply a bisexual and dynamic character, Orlando, but to create a
character who is multisexual” (13).

** de Gay, Jane. 
"Virginia Woolf's feminist historiography in Orlando." Critical
Survey, vol. 19, no. 1, 2007, p. 62+. Literature Resource Center,
go.galegroup.com/ps/i.do?p=GLS\&sw=w\&u=cuny\_gradctr\&v=2.1\&id=GALE%7CA166777311\&it=r\&asid=2ce2284ae1ec2590731d1a224e887916.

“Within her fantastic narrative and through her protagonist, a writer
who lives for 350 years and changes sexes part-way through, Woolf
traces the changing conditions for writers, and reflects upon the
effect of gender on their experiences. Furthermore, by incorporating
parodies of literary and social history and biography into Orlando
Woolf also critiques scholarly apparati for viewing the past, thus
developing her ideas about the writing and rewriting of history. This
article will demonstrate that Woolf alludes and responds to specific
debates about the form literary history should take; the significance
of the past to the present; and the importance of the imagination in
engaging with the past” (63).

Woolf satirizes the “spirit of the age”, periodization, Ruskin,
Stephen.

“Orlando, therefore , enacts the imaginative sea rch to rediscover
lost or igins which Woolf had advocated in A Room of Ones Own, by
using Orlando's long life to trace a heritage for a twentieth-century
woman writer back to the Renaissance. In satirizing the methods of
Stephen and Ruskin , she rejected Victorian patriarchal
metanarratives, which had left out the history of women writers and
had attempted to package the past in ways which reinforced patriarchal
ideologies. Instead she inclines to a school of critics who sought to
tap into the past and release its energies, and who used the
strategies of fiction to bring history alive and make it live in the
present. By placing Woolf 's feminist historiography in the tradition
of Pater and Lee, we can see why Woolf made her fulllest and most
sustained attempt to rewrite history in Orlando rather than in a
nonfictional work: for Woolf, the imagination provided the only
satisfactory medium for embracing the lost past” (71).

** Hovey, Jaime.
“‘Kissing a Negress in the Dark’: Englishness as a Masquerade in
Woolf's Orlando.” *PMLA*, vol. 112, no. 3, 1997, pp. 393–404. *JSTOR*,
[www.jstor.org/stable/462948](http://www.jstor.org/stable/462948).

“Given the extent to which ideologies of national inclusion depend on
equating gender with the performance of heterosexual respectability
and equating national affiliation with notions of racial belonging,
one might conclude that gender and nationality can operate as
essentializing ideologies of identity only if sexuality and race
remain nationality's half-hidden or forgotten others” (393).

“Virginia Woolf's Orlando (1928) can be read as an ambivalent
articulation of English nationalism in the 1920s, an era in which the
essentializing imperatives of an Englishness "at once less imperial
and more inward-looking, more domestic and more private" (Light 8\)
came to preoccupy the English public” (394). “Orlando seeks a place of
national belonging for the polymorphously sexual, masculine identified
white woman” (394).

“Butler argues that gender depends for its intelligibility on the
difference it supposedly creates and on exclusions it seeks to hide
(Bodies 39). Sexuality and other dimensions of identity, such as
nation and race, are seen as performed through gender, and gender is
seen as performed through them” (397).
	  
	Besides costume, humor also works as a masquerade to subvert
	traditional gender roles (398).

“From the first page of Orlando, the narrator stabilizes Orlando's
indeterminate gender by articulating his masculinity within the
racialized terms of national identity” (398).

“Orlando critiques whiteness and heterosexuality ambivalently and
unevenly; it uses racially and sexually "foreign" subjects to explore
the ambiguous national and social identity of a queerly gendered white
Englishwoman, excluded from the nation by her polymorphous sexuality.
Beginning with an image of a decapitated Moor, Orlando appropriates
the exoticized subjects of colonial discourse to create for its
protagonist a sexuality that is not bourgeois or heterosexual.
However, Orlando's playful but insistent production of white
femininity allows the protagonist to pass as respectable and
heterosexual by displacing her transgressive sexuality onto racial
others, thereby masking Orlando's masculine-identified literary and
sexual desires. The "playful" exchange of racial others for sexual
tolerance allows the novel both to interrogate and to affirm the
national belonging of the queerly gendered Englishwoman…” (398).

“Orlando slyly invites readers to unmask the "joking" terms under
which femininity is produced--as gender identities are often, if not
always, produced--as both an adaptation and a contestation of the
constraints of national, racial, and sexual inclusion” (403).

** Knopp, Sherron E. 
“‘If I Saw You Would You Kiss Me?": Sapphism and the Subversiveness of
Virginia Woolf's Orlando.” *PMLA*, vol. 103, no. 1, 1988, pp. 24–34.
*JSTOR*,
[www.jstor.org/stable/462459](http://www.jstor.org/stable/462459).

“Yet the extent to which Vita and Virginia did love each
other-profoundly and, in every sense of the words, erotically and
sexually (the frequency or infrequency with which they went to bed is
irrelevant)-is something that continues to be resisted, denied,
ignored, qualified out of significance, or simply unrecognized, even
by the feminist revolution that has enshrined Virginia as its saint.
There seems to be an unspoken agreement that whatever else one might
call Virginia--asexual, bisexual, androgynous--she was not a
"sapphist."” (24-25). “The assumption seems to be that lesbian love is
only or primarily sexual, that love involving the emotional intimacy
of minds and hearts requires a different term” (25).

“But to see just how large and attached to life Orlando is, one must
first get the relationship between Virginia and Vita right and then
see it in context: what it meant to regard oneself as a lesbian (or,
to use the term Virginia and Vita prefer, sapphist) and to engage in
lesbian relationships in the 1920s and what it meant to write about
one's perceptions and experiences” (25).

Examines the letters for passion and relationship between Vita and
Virginia: “Far from being a way to create distance in the
relationship, Orlando was a way to heighten intimacy-not a substitute
for physical lovemaking but an extension of it” (27).

“But what is the "sexual theme"? Orlando is obviously not about the
sapphic love of Vita and Virginia, even in a disguised way. The
hero/heroine loves men and women over the course of four hundred
years, but no one of these is the subject. The central relationship is
between Orlando and the Biographer, but although Virginia acknowledged
the erotic pleasure it gave her to think and write about Vita, there
is nothing overtly or even covertly erotic in the relationship between
Orlando and the Biographer in the novel. If Orlando has any claim to
be regarded as a lesbian novel, it is one of the best kept secrets in
literary history, having eluded even those who should be the first to
know” (28-29).

“Orlando is not a woman acting "like" a man: Orlando is a man. And a
woman. The situation admittedly puts a strain on conventional language
and thinking, but there is nothing "unnatural" about it. Orlando takes
the "dual personality" Vita described in her diary and transforms the
"brutal" side that loved Rosamund and Violet into the romantic passion
of a Renaissance nobleman, while the "seraphic," "childlike" side
capable of "years of marriage" becomes the Victorian woman who marries
Shelmerdine/Harold Nicolson with all due respect fo nineteenth-century
standards of female behavior” (30).

“Sasha, the Russian Princess, haunts the memory of Orlando the woman
as powerfully and pervasively as she dominates the passions of Orlando
the man...Even minor female characters like the prostitutes Nell,
Prue, Kitty, and Rose (216-22) have a serious dignity not bestowed on
more prominent male characters. The anomaly of Orlando's marriage to
Shelmerdine, in fact, occasions the clearest acknowledgment of theme
in the novel: ‘She was married, true; but if one's husband was always
sailing round Cape Horn, was it marriage?’” (31-32).

** Micir, Melanie.  
"The queer timing of Orlando: a biography." *Virginia Woolf
Miscellany*, no. 82, 2012, p. 11+. *Literature Resource Center*,
go.galegroup.com.ezproxy.gc.cuny.edu/ps/i.do?p=GLS\&sw=w\&u=cuny\_gradctr\&v=2.1\&it=r\&id=GALE%7CA316796566\&asid=aa986d170928fe9504f38202433d90e7.

“The possibility that one might now understand Orlando as only a love
story limits Sackville-West's importance as biographical subject and
reduces the formal difficulty of Orlando to scarcely more than a set
of references to "the love that dare not speak its name," which, once
decoded, becomes unworthy of study except as biographical evidence. In
this way, one queer reading actually diminishes the larger
stakes--both feminist and queer--of the text.”

“I want to suggest the expansion of these approaches to Orlando
through renewed attention to genre: specifically, to the book's often
overlooked subtitle, "A Biography." Woolf's revision and expansion of
biography's generic codes in Orlando make it a uniquely important text
to revisit in light of contemporary theorizations of queer
temporality. In this brief essay, I foreground what I think of as
Orlando's queer time in relation to biographical form, and I
demonstrate the resonances between Woolf's critique of the generic
conventions of biography and contemporary queer critiques of the
institutions of what Lee Edelman has called "reproductive futurism."”
“Queer temporality studies critique understandings of time as a
naturalized, internalized, bodily performance of the too easily
accepted social scripts that govern our lives, asking us instead to
recognize and resist--in our scholarly practices as in our lives--the
standard, heteronormative, biologically-driven temporal organization
of our world.”

“Biography, as a literary genre, is the gatekeeper par excellence of
reproductive time, and it is difficult to extract oneself from the
normativizing pull of biographical form.” “If biographies tell
individual life stories, so the modernist critique goes, then there is
no reason why all biographies must follow the same deadening, if
factually accurate, formal structure.” “Modernist biographies, like so
many modernist novels, highlight the individual, subjective experience
of time in order to dissociate the multiple "lives" of private
individuals from the unified "times" of public, historical record. If
one of the projects of modernist biography is to represent more than
"six or seven selves" in any given individual, then this taxonomy of
people-in-time in Orlando indicates Woolf's refusal of Victorian
biography's insistence upon documented fact and its reliance upon the
standard chronology of "every normal human system." In Orlando, she
demonstrates the power of fiction to stretch understandings of what
constitutes the "normal" in biographical writing.”

“Disrupting this form is not a merely literary decision; though
playfully undertaken, this is not mere play: for Woolf, rupturing the
generic conventions of biography is a means of unseating the keystone
of normativity itself. I am suggesting that Woolf's questions are
still contemporary questions: how can one escape--or at least
shift--the weight of standard time, standard expectations, standard
lives?” “Woolf may have begun Orlando, the first of her biographies,
as a joke, but the stakes of her project were quite serious. Should
conventional understandings of temporal progression govern the
representation of individual lives? Or should the normative milestones
of standard time be subordinate to other methods of representing the
subject,...”

“In Orlando, Woolf frees her unconventional subject from the trappings
of a conventional, biologically-bound lifetime (and its
correspondingly conventional, chronologically-organized biography).
Orlando is part of a long history of imaginative and theoretical
attempts to set free the human experience from the shackles of
standard time. It is part of a genealogy of frustration with normative
temporalities. In rejecting and reshaping the formal conventions of
standard biography, Orlando shifts the conditions of legibility for
the queer life story.”

** Smith, V. L. 
""Ransacking the Language": Finding the Missing Goods in Virginia
Woolf's Orlando." *Journal of Modern Literature*, vol. 29 no. 4, 2006,
pp. 57-75. *Project MUSE*,
[doi:10.1353/jml.2006.0050](http://doi.org/10.1353/jml.2006.0050)"Ransacking the Language": Finding the Missing Goods in Virginia
Woolf's Orlando." *Journal of Modern Literature*, vol. 29 no. 4, 2006,
pp. 57-75. *Project MUSE*,
[doi:10.1353/jml.2006.0050](http://doi.org/10.1353/jml.2006.0050)

“...the fantastic content in the novel is directly linked to the
undecidability/impossibility of the form of the novel and of the
protagonist. That is, what happens in the novel—-the impossible story
of the protagonist rather unremarkably changing from a man to woman
and living 400 years—and what it thematizes—-language’s inability to
adequately represent the “thing itself ”—-mirrors the undecidability
of the text—-is it a biography, an autobiography, fantasy, etc.—-and
the impossibility of the form of “woman.” In other words, what is
Orlando? Is she a Woman? If so, how can she be represented? In short,
the text echoes the difficulty of representation in the difficulty of
representing woman for herself, as herself. The consequences of this
doubling of/in the text are profound: Woolf re-animates the form of
biography, produces a text where Vita can read/see herself, as can
Woolf, and enables both women to have compensatory stories of their
own. Woolf ’s work, then, suggests that a doubleness is needed to
produce the self as woman, to represent (her) self” (58).

Oneself represented through the double:
- “In what follows, I move between the real and its representation in
  order show the something “other” that Woolf builds between. I
  suggest that Woolf foregrounds the doubleness that is needed to
  produce the self as woman in language and in culture; that is,
  Virginia needs Vita to represent herself and vice versa, and this
  parallels the conundrum of language for women—-*the only way to
  represent oneself is through a doubled otherness*. In other words,
  if according to poststructuralists, language is always (at least)
  one step away from the thing itself, and if woman, according to
  feminism, occupies the space of object/thing (in culture), then
  woman is always one step away from herself as well—a twice removed
  relative of language” (59).

“the novel might be a metaphorical recovery of what Woolf and
Sackville-West could not, as women and as lovers, have” (64).

“For Sackville-West, Orlando is a compensation for losses—-a kind of
mourning for Violet/Sasha, for the loss of Knole. The novel returns
these “objects” to Sackville-West and adds the bonus of mirroring her
as a magnificent, magical figure wearing a “robe stitched in
jewels”... For Woolf, Orlando is a compensation for the loss of
Sackville-West, a mourning of her. She gets to keep a “fixed”
Sackville-West, a woman who will not betray her, as well as a vision
of Sackville-West as a kind of idealized version of herself—a woman
who could write, have children, be sexual, be aristocratic, have
affairs and do all the things that she felt unable to accomplish. On
the other hand, Woolf can criticize her for lacking a necessary
something in her writing. In this way, Woolf also critiques herself,
identifies and displaces onto another person her own fears about the
inadequacy of her writing” (67).

Bemoaning the inadequacy of language
- “If Orlando as a text mitigates a series of losses in the real world
  through rewriting, it also thematizes within the text how
  representation or, rather more particularly, how literary language
  finds itself at a loss. But like the melancholic’s recuperation of
  the lost object through constant speaking about it, the text offers
  a recuperation of the object while *bemoaning the inadequacy of
  language*. There are a number of self-reflexive examples in the
  text: the biographer’s professed inability to convey his subject,
  Orlando’s frustrated inability to describe Sasha, the failure of
  language to match Nature, the rendering of Orlando’s change into a
  woman as indescribable, and Shelmerdine and Orlando’s love which is
  described as inexpressible” (68).

“Woolf demonstrates the doubleness of language; she laments its
inadequacy while effectively and fantastically achieving her ends. At
the same time, she stages the loss of Vita while simultaneously
producing her” (69).

** Gilmore, Lois J.
"The Orlando project: claiming Woolf for the community college."
Virginia Woolf Miscellany, no. 73, 2008, p. 13+. Literature Resource
Center,
go.galegroup.com.ezproxy.gc.cuny.edu/ps/i.do?p=GLS\&sw=w\&u=cuny\_gradctr\&v=2.1\&it=r\&id=GALE%7CA297829303\&asid=a531c34ae526c0d7b57b29ccf325017c.

Appendix A--Handouts

Project Part I. Preliminary Questionnaire

1\. If you have read any of Virginia Woolf's writings, identify them and explain the context. For example, did you read them for a class? For pleasure?  
2\. If you have previously heard of Virginia Woolf or any of her writing but have not specifically read any of her work, please explain when and where you have heard of her prior to this class.  
3\. Identify any Alms you have seen that are related to Virginia Woolf's writings.  
4\. Please explain your reading experiences. Have you ever been "engrossed" in a novel? If so, what elements helped you enter the world of the novel?  
5\. What have been your best experiences studying the novel in the classroom? What elements help you understand and "appreciate" the novel?

Part II. Reading/Discussion Guide

Chapter One  
1\. At what time period does the novel begin? What are the historical events that situate the novel? Who are the historical personages Orlando meets?  
2\. Identify the narrative "voice."  
3\. What do we learn about Orlando? How?  
4\. What does the biographer say about constructing Orlando's identity? Why is it so important for the biographer to define Orlando?  
5\. Identify the major themes introduced in this chapter. How does the narrative voice introduce these themes?  
6\. What do you think will be the major symbols in the novel?  
7\. What can you say about yourself--the reader--in relationship to the novel at this point? What does Woolf do to draw you into the life and history of Orlando?

Chapter Two  
1\. What changes does Orlando undergo? Why? How does the biographer explain these changes?  
2\. Why is Orlando "done with men"?  
3\. Identify the focal points of this chapter. What details are repeated? What details/symbols do you consider most significant?  
4\. How does the theme of gender manifest in this chapter?  
5\. In what activities does Orlando engage? How would you describe Orlando in this chapter?  
6\. What are the biographer's problems and/or issues?

Chapter Three  
1\. Identify the historical time period in this chapter.  
2\. What is Orlando doing in this chapter? How would you describe Orlando in this chapter?  
3\. What is Orlando's stance toward empire? Of what importance are "place" and "geography"?  
4\. What is the biographer dealing with in this chapter?  
5\. How does clothing figure in this chapter?  
6\. What changes come about for Orlando? How? What do you think about this change?  
7\. Speculate at to what this change will mean for Orlando.

Chapter Four  
1\. What changes has her "gender" wrought on Orlando? How would you describe her? Can you identify some gender conflicts? How is your notion of gender challenged?  
2\. Has Orlando's gender changed her relationship to history? To place?  
3\. Trace the theme of "writing" in this chapter. What writers does Orlando meet? What is their attitude toward Orlando?  
4\. What difference does the return to England make? Why is the setting so important?  
5\. In what ways does travel figure in the novel?  
6\. Explain how the name of the ship Enamoured Lady illustrates the comic/ironic aspects of the novel. Can you think of any other instances?

Chapter Five  
1\. What changes occur in this chapter?  
2\. Identify the historical period of this chapter.  
3\. How would you describe Orlando?  
4\. What loose ends are tied up?  
5\. What does the biographer say about Orlando's life?  
6\. How does the romantic scenario play out in traditional and non-traditional ways?  
7\. What are some of the ironies of this chapter?  
8\. As a reader explain your relationship to the text and to Orlando.

Chapter Six  
1\. Identify the historical time period, and identify some ironies associated with the disruption of the reader's traditional expectations for the novel like plot, character, setting, theme  
2\. Do any of the details and symbols you identified as significant in question 6, Chapter One, show up in this chapter? If so, what is the importance?  
3\. What issues is the biographer dealing with in this "final" chapter?  
4\. Explain how the plot is resolved.  
5\. In what ways is Orlando the same? In what ways is he/ she different? What are the differences in the ways men and women relate to time and place? How are these gender issues resolved?  
6\. On what day and time does the novel "end"?

Part III. Group Projects

The purpose of this assignment is to add depth and perspective to our study of Virginia Woolf's novel Orlando. There are two components to the Part III assignments: 1\. a written analysis of findings, a portfolio of material, and a bibliographic list of sources; 2\. a brief (5-10 minute) presentation of your findings. Each group should work together to clarify the purpose, design of the project, and divide the tasks. The final project will be submitted and graded as a group project. The oral component may be assigned to a single member of the group, and it must be given to the class on the designated date.

Choose one of the following topics:

1\. Significance of Place: Investigate the various locations prominent in the novel and how they relate to plot or character.

2\. Fact and Fiction: Fact, as Woolf shows, is an utterly subjective quality. What is unable to be proven by letters and documents may certainly still be fact. And what seems to be completely objective, like the dates of birth and death, is entirely arbitrary. Investigate the construction of fact and fiction in the novel. 

3\. Gender & Representation: Investigate the ways in which clothing constructs identity, gender, and power. How do the details of ordinary reality and physical appearance construct identity and truth? What other elements construct identity?

4\. Spectacles of Empire & Power: Investigate the historical pageants like the Great Frost, the visits of Queen Elizabeth I, the relationship between Britain & Turkey, World War I.

