** prosser's critique of butler

This desire "simply, to be" perhaps explains why Queer Studies tools
are not well suited to studying trans investments. Despite its
focus--indeed, obsession--with gender and sexuality, Queer Studies has
a history of overlooking the body, the experience of gendered
embodiment, in favor of discursive explorations and forms of gender.
One of Queer Studies' sharpest tools, the field-defining concept of
Gender Performativity, for example, has been thoroughly critiqued by
Trans Studies scholars like Prosser. Prosser argues that while Gender
Performativity takes gender crossing seriously, the material body
often remains irrelevant to this theorizing. In a trenchant critique
of Butler's reading of Venus Xtravaganza, who Butler argues is a
subversive figure, Prosser points out that Venus's /subversion/
depends on how one reads her transsexuality: whether one reads Venus
as how she indicated she wanted to be read, that is, as a woman, or
whether one reads her as an "incomplete" MTF transsexual. Prosser
explains that "What matters for Butler is the oscillation between the
literality of Venus's body and the figurative marks of her gender"
(49). As a result, Prosser argues, "Butler figures Venus as subversive
for the same reason that Butler claims she is killed," a stance that,
according to Prosser, "verges on critical perversity" (49).

For Prosser, what matters is not that Venus's body occupied an
ambiguous space between here and there, a space which has been
alternately literalized and metaphoricized in dizzying movements
toward and away from the sexed body, but rather than transsexuality is
discussed in terms of that which it avoids: subversion. Prosser points
out that Gender Performativity's focus on boundary crossing "cannot
account for a transsexual desire for sexed embodiment as /telos/"
(33). In other words, it cannot account that for Venus "her desire--to
be a complete woman for a man--is heterosexual, and it is more this
desire in combination with her transsex that kills her" (Prosser 47).

More overtly than Queer Studies, Trans Studies foregrounds how the
desire for normativity, the desire to pass, inflects the experience of
embodiment, and especially of embodied disjunction, what is often
referred to as gender or body dysphoria. Here, Prosser offers a useful
model characterizing dyphoria as a conflict between the physical body
and what he calls the "body image" (12). While the physical body is
what we already know as the corporal mass of the body, the body image
is an internal representation of this corporeality, one that comes
with its own set of somatic registers. Despite being internal, the
body image is experienced as a sensual phenomenon, emerging in
surprising ways on the surface of the body. This body image, according
to Prosser can "transform fleshly matter and inscrib[e] its struggle
on the material body... exterioriz[ing] what is conceived as internal"
(71). His example of this phenomenon comes from the memoir of Raymond
Thompson's autobiography, /What Took You So Long?/ (1995), from a
scene where the author experiences the physical body as a "false outer
skin" that encloses the true "inner body," the body image (69):
#+begin_quote
In a remarkable instance of quasihysterical symptomization, Thompson's
narrative literalizes this psychic/corporeal inside-out-ness. Rising
from his bed, seeing his reflection in the mirror, Thompson finds his
face covered with weeping blisters... Not simply marking the
dissociation between physical body and body image, the blisters
reproduce in their very microstructure that dynamic of an inner body
pushing up against, trying to escape from the material outer body:
vesicles filled with bodily fluids bursting up and out from their
internal course through to the body's surface, overflowing their
assigned passage. 71
#+end_quote
In this narrative, Prosser explains, the blisters manifest the
"conflict between the true body within and the false body without,
between sentient body image and insentient visible body" (70).
According to Prosser, the body image "clearly has a material force for
transsexuals," one that often manifests in the trope of being "trapped
in the wrong body" and feelings of dysphoria (69).

That trans experiences are driven by a desire for embodied belonging
is one way that it distinguishes itself from queer, which historically
has sought subversion and rebellion. This key difference between queer
and trans opens a natural alliance between trans and cis subjects, as
the next section endeavors to demonstrate through close readings of
the cisgendered dating show, /Love Is Blind/.
** you're not their mommy
The concept of touch being scary emerges in one scene between Paul and
Micah, a newly engaged couple who are one day into their pre-wedding
romantic getaway, in Mexico. They are swimming in a freshwater pool,
when Micah notices a fish, which she mistakes for a small shark,
#+begin_quote
Micah: Is that a shark?

Paul: What do you mean shark? Oh, they're catfish. They look like
baby, like, tiny nurse sharks.

Micah: Okay, this is kind of scaring me. It's my worst nightmare if
one touches me.

Paul: These little catfish?

Micah: Yeah.

Paul: You're not their mommy.

/Love is Blind/, Season 4, Episode 5, "Paradise Lost"
#+end_quote
Here, the word "touch," which appears in the same sentence as "my
worst nightmare," accrues an association with fear and revulsion. It
is also, interestingly, associated with the concept of motherhood, in
the statement from Paul, "You're not their mommy". This association
between Micah and motherhood (or the lack thereof) haunts the couple
until the renunion episode, which I discuss in this chapter's
conclusion. At the end of the show, Paul rejects Micah directly on the
altar. The reason, he later explains, is because he "struggled with...
envisioning Micah as, like, you know, a mother" (Season 4, Episode 12,
"Eternal Bliss?").

The disruption of bodily integrity has ramifications that last well
beyond the pods. Recalling the case of Paul and Micah, Paul eventually
rejects Micah because he wanted more evidence of maternal qualities.
In his own words, he "struggled with... envisioning Micah as, like,
you know, a mother" (Season 4, Episode 12, "Eternal Bliss?"). At the
end of the season, when the host of the "Reunion" episode prods him on
the topic, he struggles to articulate his reasoning:
#+begin_quote
Paul: You know, she didn't feel comfortable with showing that side of
her.

Host: I thought she said she did. She just talked about it from since
the pods up until your wedding day.

Paul: It wasn't evident to me… That wasn't there.

Host: You wanted actions. Like, you wanted her...

Paul: I just wanted to be able to see it, I guess. Like...

Host: What would make you see that? I'm sorry. Just so I understand.

Paul: I think... It's a little bit ineffable, right? So, it's kind of
an exuding, a nurturing presence. It's something that you feel.
There's not really, like... tangible, kind of like, things, I don't
think. (Season 4, Episode 13  ‘The Reunion")
#+end_quote
Paul claims that he failed to "see" evidence of Micah’s motherly
nature, but when asked to explain what this evidence would look like,
answers that it is "ineffable." He supposedly wants someone who can be
a mother, but cannot describe what a mother looks or acts like. What
he wants Micah to have expressed, he cannot express himself. At the
end, he takes refuge in the sense of /feeling/, in the untraceability
of felt sensation.

Clearly, Paul's answer demonstrates that some cis people, besides
being firmly anchored to their genders, are not okay in their bodies.
That being said, however, I am not interested in a critical analysis
that redeems them or their bodily experience. After all, cis-hetero
bodies are already well represented and redeemed. What I am interested
in, rather, is the study of normativity, and how alignments between
cis and trans experience might further this study.

** konya et al

[MOVED But AI can find common ground, Konya]



    ADD evidence: Konya, 2025: "Using collective dialogues"

    "AI-assisted methods... can help navigate polarization and surface
    common ground in controlled lab settings"

    Using AI "to find common ground between Israeli and Palestinian
    peacebuilders in the period following October 7th, 2023."

    "The process resulted in a set of collective statements, including
    demands to world leaders, with at least 84% agreement from
    participants on each side."
