* Counter-Code: Computational Methods for Working with Language
** topic:
- Computational methods for working with text about queerness.
  
** book questions:
1. What do concepts from Queer Studies and adjacent fields offer to
   computational tools for working with text?
2. How do computational methods constrain the expressive potential of
   language into data?
3. How do concepts from Queer Studies and adjacent fields work against
   constraints in text data?

Template answers to questions:

1. What do concepts from Queer Studies and adjacent fields offer to
   computational tools for working with text?
   - [queer theory concept], offers an approach to [computational
     tool] that [does this to text].
     1. The Queer Studies concept of Gender Performativity offers an
        approach to text analysis that surfaces multiplicity in
        language meaning.
     2. QOCC's concept of dis-identification offers an approach to
        textual markup that delineates irreconcilable interpretations
        of language.
     3. Black Feminist Studies' concept of the flesh offers an
        approach for analyzing software that is grounded in the
        physicality and materiality of screen display.
     4. Trans Studies' concept of normativity offers an approach to
        text generation that reveals shared investments across
        identity and subject groups.

2. How do these computational tools constrain the expressive potential
   of language into data?
   - [Constraint] [does something] to language [to make it this].
     1. In text analysis, "loops" strips language of idiosyncracies in
        order to count its common features.
     2. In textual markup, "tags" disambiguate and fix language to
        sort it into discrete elements within an ordered hierarchy.
     3. In text display, layers of computer software displace language
        processing away from human awareness in order to streamline
        interface effects.
     4. In text generation, algorithmic prediction aggregates language
        expressions to generalize and approximate patterns of language
        use.
	
3. How do concepts from Queer Studies and adjacent fields work against
   constraints in text data?
   - Queer studies [concept] [does a thing to work within and against
     constraint]
     1. From the concept of iteration, the emphasis on repetition
        inspires a text analysis practice that multiplies and
        re-signifies word meaning.
     2. From the concept of dis-identification, the appropriation of
        dominant codes influences a markup strategy that delineates
        the gaps between tagging structures.
     3. From the concept of the flesh, the foreclosure of depth
        suggests reading layers of software as intimate and physical
        screen effects.
     4. From the concept of normativity, the desire for conformity
        guides analysis toward shared investments between polarized
        perspectives.
** book argument
Concepts from Queer Studies and adjacent fields offer methodological
approaches to computational tools that work with text-based data. Such
tools, which are used for tasks like text generation, preservation,
and display, tend to constrain language about gender, sex, and
sexuality, stripping its idiosyncrasies and ambiguities, to turn it
into computable units of data. Queer Studies and adjacent fields
inspire methodologies for working against these
constraints---methodologies that destabilize authoritative and
delimiting structures, and open novel readings of language data. By
engaging closely and attentively with these computational processes,
users can resist the reductive ways that technology works upon
expression.

** evidence
*** main examples or case studies:
- Computational tools and underlying processes.
- Theoretical concepts from minoritarian fields, queer theory mostly.
- Literary sources.
- Critical work in DH and Media Studies

*** chapter by chapter evidence base
- Chapter 1: Refers to text analysis methods and processes, the loop
  in python programming, word vectors, Queer Theory's concept of
  Gender Performativity, V Woolf's Orlando.
- Chapter 2: Refers to text encoding practices and projects, the XML
  data structure, Queer Theory's concept of dis-identification, Oscar
  Wilde's MS for The Picture of Dorian Gray.
- Chapter 3: Refers to media archaeological theory and practices,
  Black feminist studies theory, software layers and abstraction,
  Octavia Butler's Dawn and Entropy8Zuper's skinonskinonskin.
- Chapter 4: Refers to ML/text generation methods and practices, ML
  processes of training, Trans Studies theory on normativity and
  embodiment, popular discourse on transphobia and Reality TV.

** chapter snapshots
- Chapter 1:
  - topic: text analysis and gender
  - scope and evidence type:
    - Computational text analysis algorithms like Logistic Regression,
      Burrow's Delta, semantic similarity
    - Queer Studies' theory of Gender Performativity
    - Woolf's /Orlando/, (Rosenberg's /Confessions of the Fox/ or
      /Nightwood/ or /Fun Home/). 
  - main claims:
    - claim: Text analysis methods that reduce complexity and
      variability of gender expression into binary forms can be
      "iterated" through different vantage points (close and distant)
      to surface multiplicity.
      - That dominant methods in text analysis use algorithms in a
        way that close off the kinds of readings we can peform on
        gender.
      - Python processes text to diminish peculiarities and move
        toward abstract connections.
      - One can iterate over binary structures in algorithms to open
        up, rather than collapse, possible associations in gender
        terms.
  - metacommentary:
    - Words have inherent multiplicity, meaning is always expanding
      beyond the binary. (But also, meaning is discursive,
      disembodied--lacking material realities, whitewashed).
- Chapter 2:
  - topic: text encoding and sexuality
  - scope and evidence type:
    - textual scholarship and queer historiographical approaches to
      preservation.
    - TEI technology and projects that attempt to markup complex
      sexual IDs,
    - The first 3 chapters of the manuscript of Dorian Gray (maybe
      /Nightwood/, /Confessions/).
  - main claims:
    - TEI imposes not just disambiguation between elements but also a
      power structure which delimits what can and cannot be said.
    - Hierarchical formats that categorize data can also suggest
      implicit power structures that delimit what is sayable and
      permissable.
    - We cannot mark up what has been lost, but we can see our own
      complicity in power structures.
  - metacommentary:
    - Meaning is inherent in organization and structure, controlling
      what can and cannot be signified. (Markup, inclusion into
      systems, isn't enough).
- Chapter 3:
  - topic: text display and sex (intercourse)
  - scope and evidence type:
    - Media archaeology theorizing on materiality.
    - Black feminist theorizing on the flesh.
    - The novel /Dawn/ by Octavia Butler and the electronic literary
      work, /skinonskinonskin/ by /Entropy8Zuper/.
  - main claims:
    - The collision between thinking and feeling surfaces the tension
      of where is sensuality.
    - The surface (screen layer) of computing obscures the depths of
      material processing. 
    - Across layers of display and source code, surface effects are
      unmappable, fugitive, displaced, enabling significatory
      possbilities (connectivity, intimacy) that resist technological
      constraints. The pairing down to surface enables connectivity,
      intimacy.
      - Materiality exists even in abstracted forms, and points to
        significatory possibilities that resist circumscription.
  - metacommentary:
    - The materiality of the sign offers a way of working within
      reductive signification processes.
- Chapter 4:
  - topic: text generation and sex (gendered embodiment)
  - scope and evidence type:
    - Trans studies on normativity and embodiment
    - Machine learning technology and training process
    - Popular, online journalism and reality tv
  - main claims:
    - Machine learning is a tool of approximation, reducing meaning to
      common denominators and flattening perspectives to univocality.
    - It can be used to find similar investments across polarizing
      perspectives.
  - metacommentary:
    - univocality is a way of finding shared investments.

** organizing principle
Each chapter takes a different process for working with text,
identifies a computational constraint that reduces textual detail in
some way, and finds a way of working the constraint into a
close-reading practice.

- process for working with text -> constraint
1. text analysis -> iteration (loops)
2. text encoding -> containment (tags)
3. text display -> abstraction (display)
4. text generation -> aggregation (prediction algoirthms)
   
- constraint -> what it does to data -> how to resist 
1. iteration -> regularizes/homogenizes data -> repeat with difference
2. containment -> leaves out data -> narrate between gaps
3. abstraction -> displaces data -> close reading source code
4. aggregation -> averages data -> finding common ground

** topic, claim, and metacommentary
Chapter 1:
- topic: Text analysis and gender
- claim: Text analysis methods that reduce complexity and variability
  of gender expression into binary forms can be "iterated" through
  different vantage points (close and distant) to surface
  multiplicity.
- metacommentary: Words have inherent multiplicity, meaning is always
  expanding beyond the binary. (But also, meaning is discursive,
  disembodied--lacking material realities, whitewashed).

Chapter 2:
- topic: Text encoding and sexuality
- claim: Hierarchical formats that categorize data can also suggest
  implicit power structures that delimit what is sayable and
  permissable.
- metacommentary: Meaning is inherent in organization and structure,
  controlling what can and cannot be signified. (Markup, inclusion
  into systems, isn't enough).

Chapter 3:
- topic: Text display and sex
- claim: Materiality exists even in abstracted forms, and points to
  significatory possibilities that resist circumscription.
- metacommentary: HOWEVER, the materiality of the sign offers a way of
  working within reductive signification processes.

Chapter 4:
- topic: Text generation and embodiment
- claim: Approximation of meaning finds commonalities between
  polarized perspectives.
- metacommentary: HOWEVER, univocality is a way of finding shared
  investments.

** the market
*** competing or comparable books
Please provide the title, author, date of publication, publisher and
price of three to five comparable books that compete directly for a
reader’s attention.

What contribution do these books make to your field of research? What
are you doing that improves upon and sets your work apart from each of
these books’ contribution?

If there is no direct competition, explain why. Has the topic only
been covered in a chapter elsewhere? Is this the first book-length
treatment of it?

**** jacob gaboury
**** heavy processing


**** queer data studies
Patrick Keilty, Ed. /Queer Data Studies/. University of Washington
Press, 2024. $30.00

This book is the only substantial treatment of the field of Queer Data
Studies. It comprises a collection of essays organized around the
theme of "queer data," which is taken up in a variety of contexts,
including Black Studies, machine learning, sex work, HIV Studies, and
Science and Technology Studies (STS). This book's main contribution is
its critical stance on data, pointing out that "Queer people have
complex, sometimes contradictory relationships to data" (11). It
explores common heuristics, like opacity, ephemerality, and messiness,
within Queer Studies and related fields, and how these inflect topics
of surveillance, privacy, autonomy, and soverignty in data.

As an edited collection, however, there cannot be a sustained
examination of digital tools or processes involved in working with
data, which is where my own project intervenes with its deep readings
of computational mechanism.

Additionally, my book's expansion beyond the field of Queer Studies
puts concepts like embodiment and the flesh, from Trans and Black
Feminist Studies, into orbit with Queer Studies. 


**** Bonnie Ruberg, Video Games Have Always Been Queer, NYU Press 2019.
Catalogued: Postmillennial Pop / media & technology / sociology
**** Cait McKinney, Information Activitsm: A Queer History of Lesbian Media Technologies, Duke U Press 2020. 
Catalogued: Media Studies > Media Technologies, Gender and Sexuality >
LGBTQ Studies, Activism


** book narrative outline
Paragraph 1: What does my book as a whole do?
- [X] my book's topic: Computational methods for working with language
  about queerness.
- [X] book argument (see above)
- [X] implicit lesson:
  - By engaging closely and sensually with a technology, we can find
    ways of resisting its reductions, the ways it works upon us.
  - Experimenting with how something works in depth and in a sensual
a    way will liberate us from being used and being users
- [X] To answer this question, I apply concepts from QS and related
  fields to work against constraints in computation using examples
  from literature as my test case. [or see evidence base above].

Paragraph 2: How does this book as a whole proceed? (how do the
arguments unfold over the chapters)
- [X] organizing principle (see above): Each chapter takes a different
  process for working with text, identifies a computational constraint
  within that process, and finds a way of working that constraint into
  a close-reading practice.
- [X] narrative arc (chapter 8)
  - moving from simple concepts to the complex processes.
    - introducing humanists to how computers work on a fundamental
      level. We start with the simple, with counting and categorizing,
      then we get deeper into stacks and machine learning.
    - the first two chapters are about simpler processes, counting and
      tagging, and the latter chapters are about more complex
      processes, abstraction and prediction.
      - I see other parallels between the two parts: the first part
        being about creating destabilization, and the second part
        about re-stabilizing; the first about queer theory and its
        methods, the second about adjacent fields and it's methods.
- [X] describe book structure (chapter 11):
  - The book is divided into two parts: part one, which explores core
    concepts in computation: chapter 1 explores counting, which is the
    bedrock of all analysis tasks; chapter 2 explores tagging which is
    the foundation of data formatting and structure. Then, part two
    explores more complex processes: chapter 3 explores
    interface/display processes, and chapter 4 explores text
    generation. The second half builds on concepts from the first to
    show more complex tools. Word vectors (ch 1) -> neural net
    training (ch 4), markup languages (ch 2)- > html code interacting
    with javascript (ch 3).
    
Paragraphs for body chapters:
- [ ] what does this chapter do in service of the book?
- [ ] start with a topic sentence from "what stays the same, what
  changes": 
  - from chapter one to chapter two: We move from text analysis to
    text encoding, from counting to markup. They are both basic,
    foundational acts of working with text data, but while analysis is
    about regularizing data to be counted, markup is about appending
    descriptive information to sort and structure data.
    - Impact:
      - Markup shows the implicit ways that data formats pre-
        determine what kind of information can be contained within
        them. This information has to do with power structures that
        delimit what can and cannot be said. "Occluding whiteness".
      - It also brings to the surface (in another way) how QS has
        looked over race and materializations. In the previous
        chapter, we found that the trope of fluidity overlooks
        material reality. In this chapter, we find that there is no
        formalization that will recuperate what has been left out of
        the structure. That the task must be otherwise.
  - from chapter two to chapter three: Looking at a more complex
    process, which is abstraction and display of data. Moving into
    Black Feminist studies, to find ways of addressing material
    concerns. We return to the materiality of the word, a stabilizing
    force.
    - Impact:
      - Now we can really "go deeper" than we did in previous
        chapters, where we merely dipped our toes.
      - We are zooming out to look at how a larger process, of
        abstraction, works on data. There is more complexity, we've
        learned more about how computation works to get here,
        regularizing data, plain text formatting, in particular, which
        helps the reader understand data stacks and how they work.
  - from chapter three to chapter four: Looking at algorithmic
    prediction and how that works to normalize data, similar to what
    we discussed in the first chapter. Moving to Trans Studies, to
    address underlying investments in normativity.
    - Impact:
      - The approximation of language revealing shared investments
        across political poles. Like the previous chapter, something
        shared, something solid.
- [ ] chapter snapshots (see above) on scope, evidence, and claims. 
- [ ] book answers for each chapter (see above)
 
** TODO book narrative
Queer Computing / Queerware / Counter-Code

Methods for Resisting Computational Constraints of Text-based Data; Re-thinking language tools; Queer Deviance and the Reimagining of
Language Technologies; Queer and Feminist Revisions of Language
Technologies; Close reading language technologies to destabilize
power. 

This book explores computational processes that work with text. It
applies concepts from humanities fields to push against the ways that
computational processes reduce and flatten the complexity of language
data. It shows how certain computational tasks, like text generation,
preservation, and display, tend to constrain the expressive potential
of language, stripping its idiosyncrasies and ambiguities, to turn it
into computable units of data. Humanities fields like Queer Studies,
Black Feminist Studies, and Trans Studies inspire methodologies for
working against these constraints---methodologies that destabilize
authoritative and delimiting structures, and open novel readings of
language data. In its experiment with these new methodologies, this
book uses examples of Queer literature as a test case, applying
methods to elements of gender, sexuality, sex, and the body in
computational structures and processes. By engaging closely and
attentively with these computational processes, the reader discovers
tools for resisting the ways that technology works upon language,
moving simultaneously with and against the system which constrains
meaning.

Each chapter of this book takes up a computational process for working
with text, and uses it to study a component of queer identity,
expressed in a work of Queer Literature. For every computational
process, the chapter identifies a constraint---a mechanism that
transforms and reduces the component of queer identity into computable
data. The earlier chapters focus on basic processes, like counting and
tagging language data, to study gender and sexuality, while the later
chapters move toward more complex processes of visual display and
algorithmic prediction to explore sexed materiality and embodiment.
Chapter one, "Counting Text," uses text analysis to study gender in
Virginia Woolf's /Orlando: A Biography/. Chapter two, "Tagging Text,"
turns to text preservation methods to trace the suppression of
homosexuality in Oscar Wilde's novel, /The Picture of Dorian Gray/.
Then, the third chapter "Text Display," reads examples of sensuality
and physicality acrosss print and electronic formats, in Octavia
Butler's novel, /Dawn/, and a work of electronic literature, entitled
/skinonskinonskin/, by the net artist, /Entropy8Zuper/. Finally, the
fourth chapter, "Text Generation," experiments with algorithmic
prediction to analyze gendered embodiment in an reality TV dating
show, /Love is Blind/. Moving from canonical works of Queer Literature
and Queer Theory in its early chapters to more eclectic source
material, like science fiction and reality TV in the latter chapters,
this book expands the repertoire of "Queer" beyond its now
instiutional use. Developing queer for the future, the book argues,
involves cooperation across adjacent fields like Trans Studies, Black
Feminist Studies, and Latinx Studies. 

Chapter One, "Counting Text," explores text analysis to study gender.
It examines a core operation of text analysis, which is counting, or
compiling word freqencies and patterns through context and assocation.
This chapter delves into the process behind counting text, identifying
the core concept of the "loop," which repeats the same action to a
collection of text, one word at a time. This mechanism, which enables
text analysis processes to remove idiosyncracies and details from
text, flattens text data into a standardized, computable form. The
chapter then explores possibilities for handling this constraint,
turning to the theory of Gender Performativity, from Judith Butler's
book, /Gender Trouble: Feminism and the Subversion of Identity/
(1990), widely cited as an inaugural text of Queer Studies. Similarly
to text analysis, gender performativity is based on a cyclical
operation that repeats an exact action over and over again. The
chapter takes the iterativeness of gender performativity and its
potential for re-signifying terms, into a text analysis pratice. It
applies this practice to Woolf's novel, /Orlando/ (1928), to study the
multiplicity of gender forms in that novel. Finally, it offers some
more recent critiques of this reading and of Gender Performativity for
the way it elides questions of embodiment and materiality.

Moving from text analysis to text encoding, Chapter Two, "Tagging
Text" examines a text preservation format to study sexuality. This
protocol, the Text Encoding Initative (TEI), consists of a set of
electronic standards widely-used for encoding text-based data. The
structure of the TEI, which requires that text be sorted into rigid
categories, oragnizes textual elements into a modular components
within a hierarchical structure. Within this structure, inner or
"child" elements become disambiguated and fixed according to the
"rules" of the outer, parent element. To resist this dominating,
top-down control of the data format, the chapter turns to the strategy
of disidentification, theorized by Queer of Color Critique scholar
Jose Esteban Munoz. This concept offers a method of re-appropriation,
of "reading onesself into" a dominance structure which is intended for
exclusion (PAGE NUMBER). The chapter then applies this strategy to
encode the revisions that Oscar Wilde made to his novel, /The Picture
of Dorian Gray/ (1990), prior to its publication in 1890.
Disidentification, which works within and against majority culture,
offers a useful heuristic for grappling with the rigid boundaries of
the TEI. This approach delineate irreconcilable interpretations of
language choices in Wilde's revision process, without resolving the
coded elements of homosexuality in Wilde's text. It is an experiment
that surfaces the contours, but not the content, what cannot be
recovered. The chapter ends with a meditation on Wilde's own position
of privilege as an editor of his own text, the executor of his own
censorship, and how TEI can be used as a way of surfacing power
operations in text.

Moving from foundational processes like counting and tagging text, the
second half of the book turns to more complex processes of text
display and generation. Chapter Three, "Text Display," examines the
computing "stack," the layers of software that transport data from
storage to the screen. In order for the stack to operate efficiently,
code instruction (program code) must be separated from its execution
(computation). This environment creates an ontological state of
displacement, where every electronic action occurs at a remove, giving
the illusion that electronic processes are boundless or immaterial. To
read materiality back into the stack, this chapter borrows from two
seemingly unrelated fields, Media Archaeology and Black Feminist
Studies, both of which offer robust methodologies for reading physical
and "fleshy" dimensions of symbolic processes. Using these theories,
the chapter embarks on a deep reading of program code from an early
work of electronic fiction, /skinonskinonskin/, by Aureia Harvey and
Michaël Samyn, (1999). This work, an early example of internet or
"NET" art, consists of several "digital love letters," written in HTML
and animated with JavaScript and Flash software (/Net Art Anthology/).
The chapter's reading of this work surfaces how its screen effects,
while apparently disconnected from underlying hardware and
computational processing, offer significatory possbilities for reading
intimacy and connection over the network.

Building on the analysis of "Counting Text," or word frequencies, in
chapter one, the fourth and final chapter explores an advanced
counting processes, which is machine learning, which it uses to study
normativity. This chapter, "Text Generation," traces the steps behind
algorithmic prediction to examine what it does to language data and
how it represents word meaning in computational form. It posits the
the training process for Large Language Models (LLMs) as a tools that
/normalizes/ language, transforming word meaning into an approximate
or average forms. This process, which I examine in technical detail,
transforms word meaning into numerical scores, which it compiles from
averaging that word's various contexts from the training data. To
demonstrate this process, I train miniature LLMs from the transcripts
of a reality TV dating show, called /Love Is Blind/ (2020 - present).
In this show, the participants, who are all heterosexual and
cisgendered, are required to date each other from behind a wall,
without having access visual access to their partners until they have
agreed to get married. I then prompt the language model, which has
been trained to generate text in the same language and style of the
show participants, to answer questions about the role of the body and
embodied sensations in their dating experience. I use the language
model as a predictive instrument that can /approximate/ the linguistic
and affective patterns around the body and touch. Drawing on Trans
Studies theorizations of the body and of normativity, I argue that
participants in /Love Is Blind/--—while firmly anchored in
cisnormative frameworks—--temporarily experience a form of bodily
dissonance. This dissonance, I argue, offers grounds for theorizing
connection and solidarity beyond identity politics and polarized
points of view.

The chapters in the second half of the book offers responses to the
problems spun from those in first half: from Chapter One, the problem
of discursive forms, and how they elide embodied experiences of
gender, and in Chapter Two, the problem of power structures, which are
totalizing. Chapters Four and Three, respectively, answer these
problems by grounding in what is shared and what is material.

It shows how Queer Studies, as a field, is good at offering certain
possibilities for resistance that /disrupts/ existing structures, for
performativity and dis-identification, but other fields, like Black
Feminist and Trans Studies, offer ways of resisting that are /outside/
of the current structure. Both have advantages and disadvantages: both
are necessary for resistance work.

Core computational components from the first half of the book, like
"word vectors" and markup languages, which are essential to text
analysis and text encoding, are developed in the second half to
describe more advanced concepts, like neural nets and software stacks,
which drive processes for generating and displaying text.


Surfaces the idiosyncratic, ambiguous, and slippery qualities of
language. 

Then, with the help of Queer Studies and related fields, it re-works
the constraint into a new practice that resists this reduction of
language, and applies this practice to reading a sample of Queer
literature.
