* queer codes
** work plan (as of 8.23.26)

*** tasks

Most time intensive tasks - 3 months, 3 weeks:
- write chapter 1 - three weeks
- re-write chapter 3 - one month
- write introduction - one month
- write conclusion - one month

Less time intensive tasks - 2 months, 3 weeks:
- revise chapter 2 - one week
- revise chapter 1 - two weeks
- revise chapter 3 - one week
- revise chapter 4 - two weeks
- revise chapter 5 - two weeks
- revise introduction - one week
- revise conclusion - one week
- bibliography and style - one week

Order of tasks:
- write chapter 1 - three weeks
- revise chapter 2 - one week
- re-write chapter 3 - one month
- write introduction - one month
- write conclusion - one month
- revise chapter 4 - two weeks
- revise chapter 5 - two weeks
- revise chapter 1 - one week
- revise chapter 3 - one week
- revise introduction - one week
- revise conclusion - one week
- bibliography and style - one week

*** timeline

September:
- revise chapter 2 - one week
- write chapter 1 - three weeks

October:
- re-write chapter 3 - one month

November:
- write introduction - one month

December:
- write conclusion - one month

January:
- revise chapter 4 - two weeks
- revise chapter 5 - two weeks

February:
- revise chapter 1 - two weeks
- revise chapter 3 - one week
- revise introduction - one week

March:
- revise conclusion - one week
- bibliography and style - one week

** current task
*** TODO write chapter one - three weeks
- [X] read the chapter
- [X] come up with a TODO list:
  - [X] what parts need to be drafted?
    - to be drafted
      - intro, close reading
    - drafting in progress
      - paranoid and reparative reading
      - the protocol of capture
      - web scraping
  - [X] what order should they be drafted?
    1. paranoid & reparative
    2. web scraping
    3. protocol of capture
    4. close reading: heritage
    5. introduction
- [X] determine what needs to be read
  - [X] check readings from notes
  - [X] check zotero
  - [X] check agenda
  - [X] determine the most important ones
  - [X] order them accordingly
- books to read
  - [ ] Berlant, ed, /Reading Sedgwick/
  - [ ] Lessig, /Free Culture/
  - [ ] Warwick, /Radical Tactics/
  - [ ] /Heritage/ articles
  - [ ] Abigail Shrier, /Irreversible Damage/
- articles -- see reading notes doc

** sketch
The book experiments with Queer Studies-inflected approaches to the
digital. 

Queer practice as a way of working within constraints to open up
possibilites for alternativity, meaning, resistance.

There is a constraint, such as the reductive flattening of text in
text analysis. The hierarchical format of data structures. The opacity
of the interface, the display layer. The correlation/approximation
between features in machine learning.

These constraints are cultivated within a neoliberal logic.

Queer practice would, by contrast, seek these out and re-deploy them
toward ends they were not built for. (This "practice" element is one
way in which the book departs from others that treat similar
subjects). 

*** introduction
The stakes:
- AI: the marketing behind generative AI tools for writing and coding
  poses false solutions. The GUI will always affect and determine our
  engagement with the tool. 
  - talk of agency in building/writing
  - talk of democratizing access to coding/writing

*** Performativity / text analysis
**** critique at end of chapter:
- Amin on multiplying gender categories being a tool of patriarchy,
  and disrupting gender categories via dis-identification.
*** Dis-identification / data formats
revision:
- Look at more dynamic forms of data? (Cristina's comment)
- see [[https://en.wikipedia.org/wiki/Markup_language][markup language wiki]]

overview
- goal: markup homosexual themes that have been edited out of DG; with
  disidentification, can use TEI to mark up the "aesthetic project" of
  Wilde's revisions. 
- the revision history, the double moral
- coming up against TEI's dominance structure, which requires
  disambiguation and fixes elements.
  - dominance vs containment
  - marking up the fields
  - <gender> tag
- editorial approaches: restorative vs productive
  - feeling backward - does not try to fix, that allows things to stay
    as they are in the past, that attends to backwards, nonproductive
    feelings, and keeps them that way.
- dis-identification
  - a way of reading onesself into a system that doesn't include you.
  - We are using markup to find what has been removed, but we also
    might use it to find how Wilde adapted his work in ways to pass
    the censor, and to fit in social standards/decorum.
  - re-coding, overwriting are disidentificatory methods.
    - w can use the TEI to mark up his aesthetic project, using a
      dominance structure to mark up a system of dominance. 
- close reading of MSDG
  - the themes, the blending of themes across revision
  - afterward, some questions: 
    - can we say that OW was "disidentifying" when he coded the
      homosexual elements, or can we say that he was operating just as
      the system would have expected, that the system was created for
      this kind of aesthetic coding?
    - Wilde's power dominates this text, that is not the case for many
      others. He has gender, race, class privilege.
      - There is a power of the censor, but there is also Wilde's
        power to edit himself.
      - He makes coding into an aesthetic project. Art shouldn't be
        didactic, should never have a moral.
- conclusion:
  - Wilde's aesthetic project vs the writing beyond the tags,
    provoking the limits of containment.
  - but this doesn't work for all editorial projects. TEI can also be
    used in minimal ways. 
  - there are other ways of working within and against dominance
    structures.
    - critical fabulation is a method that imagines what is not
      recorded, what cannot have been known, writing with and against
      the archive.



*** Surface aesthetics / interface effects
Areas:
- software stacks
- electronic literature
- science fiction

Black feminist theorizing on surface aesthetics, materiality, applied
to a close reading of code and software stacks in electronic literary
work. 

For example, C. Riley Snorton's concepts of "fugitivity" and
"fungibility". "Passing" by a reduction, darker skin means can pass as
a different gender. Implies fungibility.

Racialization -- how a descent into materiality/physicality is
simultaneously an ascent into abstraction, into symbolic meaning. What
happens to objects on the screen, as they travel up the software stack?

Black Feminist Studies read other kinds of relation into this surface,
reading relations besides exploitation. For example, a denial of
access, of depth. An expression of hunger, of ingesting, taking in.

How can we take this to analyze software?

*** Seduction/correlation / machine learning
SEDUCTION

The idea that there is something seductive, that there is something
irresistable about transition. ROGD - rapid onset gender dysphoria.

The seduction of ways of thinking. The lack of critical thinking. The
lack of individual thinking. The ways that we are tied to our desires,
to our preconceptions, confirmation bias. It's the same detail that
makes a chatbot so engaging, so intriguing. A chatbot will convince a
user that it is intelligent, a user will project their desire to find
meaning onto the chatbot.

Just like that, a transphobic will project their desire onto others,
the fear of ROGD. The desire for transition becomes transformed into a
fear that transness is contagioius. I won't say whether it is or it's
not.

By creating a human-like interface, we project our desires and our
fears onto it.

CORRELATION, AFFINITY

Wendy Chun's work tracing correlation's history to a eugenic past:
these are the roots of practices we call "data science" or "data
analytics" today (check official/academic defs, check Chun's book).
Chun's work explores how they statistical methods that use correlation
emerge from pratices studying genetics and heredity for the purpose of
breeding superior humans. Despite that, Chun doesn't claim that all
correlation is inherently wrong, or that there create unjust
relations. Rather, she is more intereted in the discourse around
correlation and its utopian possibilities (check her research
questions that make this distinction).

Donna Haraway, and others, talk about using affinity as a political
method; that affinity can counteract some of the ways that what she
calls the "informatics of domination" works to subscribe and
exploit. She talks about taking the ways that informatics
compartmentalizes and organizes people and resources as an opportunity
for cultivating solidarity through affinity. Could this be a way of
creating different kinds of clusters, associations?






